#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 4 "..\..\Templates\Angular\ApiService.cshtml"
    using Tangsem.Common.Extensions;
    
    #line default
    #line hidden
    
    #line 6 "..\..\Templates\Angular\ApiService.cshtml"
    using Tangsem.Generator.Settings;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Templates\Angular\ApiService.cshtml"
    using Tangsem.Generator.Templates;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class _Templates_Angular_ApiService_cshtml : MultipleTableMetadataTemplate
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");


WriteLiteral("\r\n");




WriteLiteral("\r\n\r\nexport class ");


            
            #line 9 "..\..\Templates\Angular\ApiService.cshtml"
         Write(Configuration.RepositoryName);

            
            #line default
            #line hidden
WriteLiteral("ApiService {\r\n\r\n    construct(private httpClient: HttpClient) {\r\n    }\r\n\r\n\r\n");


            
            #line 15 "..\..\Templates\Angular\ApiService.cshtml"
 foreach (var tableMetadata in this.TableMetadatas)
{
            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n     \r\n     public get");


            
            #line 19 "..\..\Templates\Angular\ApiService.cshtml"
           Write(tableMetadata.EntityName);

            
            #line default
            #line hidden
WriteLiteral("List(): Observable<");


            
            #line 19 "..\..\Templates\Angular\ApiService.cshtml"
                                                         Write(tableMetadata.EntityName);

            
            #line default
            #line hidden
WriteLiteral("[]> {\r\n        return this.httpClient.get<");


            
            #line 20 "..\..\Templates\Angular\ApiService.cshtml"
                               Write(tableMetadata.EntityName);

            
            #line default
            #line hidden
WriteLiteral("[]>(`_api/repo/");


            
            #line 20 "..\..\Templates\Angular\ApiService.cshtml"
                                                                         Write(tableMetadata.EntityName);

            
            #line default
            #line hidden
WriteLiteral("`);\r\n     }\r\n     \r\n     public get");


            
            #line 23 "..\..\Templates\Angular\ApiService.cshtml"
           Write(tableMetadata.EntityName);

            
            #line default
            #line hidden
WriteLiteral("ById(id: number | string): Observable<");


            
            #line 23 "..\..\Templates\Angular\ApiService.cshtml"
                                                                            Write(tableMetadata.EntityName);

            
            #line default
            #line hidden
WriteLiteral("> {\r\n        return this.httpClient.get<");


            
            #line 24 "..\..\Templates\Angular\ApiService.cshtml"
                               Write(tableMetadata.EntityName);

            
            #line default
            #line hidden
WriteLiteral(">(`_api/repo/");


            
            #line 24 "..\..\Templates\Angular\ApiService.cshtml"
                                                                       Write(tableMetadata.EntityName);

            
            #line default
            #line hidden
WriteLiteral("/${id}`);\r\n     }\r\n     \r\n     public update");


            
            #line 27 "..\..\Templates\Angular\ApiService.cshtml"
              Write(tableMetadata.EntityName);

            
            #line default
            #line hidden
WriteLiteral("(id: number | string, model: ");


            
            #line 27 "..\..\Templates\Angular\ApiService.cshtml"
                                                                      Write(tableMetadata.EntityName);

            
            #line default
            #line hidden
WriteLiteral("): Observable<");


            
            #line 27 "..\..\Templates\Angular\ApiService.cshtml"
                                                                                                               Write(tableMetadata.EntityName);

            
            #line default
            #line hidden
WriteLiteral("> {\r\n        return this.httpClient.post<any>(`_api/repo/");


            
            #line 28 "..\..\Templates\Angular\ApiService.cshtml"
                                                Write(tableMetadata.EntityName);

            
            #line default
            #line hidden
WriteLiteral("/${id}`, model);\r\n     }\r\n     \r\n     public create");


            
            #line 31 "..\..\Templates\Angular\ApiService.cshtml"
              Write(tableMetadata.EntityName);

            
            #line default
            #line hidden
WriteLiteral("(id: number | string): Observable<");


            
            #line 31 "..\..\Templates\Angular\ApiService.cshtml"
                                                                           Write(tableMetadata.EntityName);

            
            #line default
            #line hidden
WriteLiteral("> {\r\n        return this.httpClient.post<");


            
            #line 32 "..\..\Templates\Angular\ApiService.cshtml"
                                Write(tableMetadata.EntityName);

            
            #line default
            #line hidden
WriteLiteral(">(`_api/repo/");


            
            #line 32 "..\..\Templates\Angular\ApiService.cshtml"
                                                                        Write(tableMetadata.EntityName);

            
            #line default
            #line hidden
WriteLiteral("`);\r\n     }\r\n\r\n\r\n ");


            
            #line 36 "..\..\Templates\Angular\ApiService.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("\r\n}\r\n");


        }
    }
}
#pragma warning restore 1591
