// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Tangsem.Generator.Templates.Angular
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using Tangsem.Common.Extensions;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Angular\NgListingComponentHtml.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class NgListingComponentHtml : Tangsem.Common.T4.T4TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\n\r\n<div class=\"two-columns-flex\">\r\n\r\n\t<!-- FILTER -->\r\n\t<div class=\"filter-colum" +
                    "n\" *ngIf=\"showFilters\">\r\n\r\n\t\t<h4>Filters</h4>\r\n\r\n\t\t<");
            
            #line 16 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Angular\NgListingComponentHtml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.TableMetadata.EntityName.Lf()));
            
            #line default
            #line hidden
            this.Write("-filter [filterModel]=\"filterModel\" (onSearch)=\"search($event)\">\r\n\t\t</");
            
            #line 17 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Angular\NgListingComponentHtml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.TableMetadata.EntityName.Lf()));
            
            #line default
            #line hidden
            this.Write("-filter>\r\n\t</div>\r\n\r\n\t<div class=\"table-column\">\r\n\r\n        <h3>\r\n            ");
            
            #line 23 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Angular\NgListingComponentHtml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.TableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write(@"
        </h3>
    
        <div>
            <button mat-raised-button (click)=""showFilters = !showFilters"">
			    <mat-icon>
			        search
			    </mat-icon>
			    Toggle Filters
		    </button>
            <button mat-raised-button (click)=""add()"">
			    <mat-icon>
				    add
			    </mat-icon>
			    New
		    </button>
        </div>
		

		<!-- TABLE -->
		<table mat-table [dataSource]=""dataSource"" matSort matSortActive=""");
            
            #line 43 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Angular\NgListingComponentHtml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.TableMetadata.PrimaryKeyPropertyName.Lf()));
            
            #line default
            #line hidden
            this.Write("\" matSortDisableClear matSortDirection=\"desc\">\r\n\r\n\t\t");
            
            #line 45 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Angular\NgListingComponentHtml.tt"
 foreach(var col in this.TableMetadata.Columns) { 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t<!-- ");
            
            #line 47 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Angular\NgListingComponentHtml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.PropertyName.Lf()));
            
            #line default
            #line hidden
            this.Write(" column -->\r\n\t\t\t<ng-container matColumnDef=\"");
            
            #line 48 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Angular\NgListingComponentHtml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.PropertyName.Lf()));
            
            #line default
            #line hidden
            this.Write("\">\r\n\t\t\t\t<th mat-header-cell *matHeaderCellDef style=\"padding: 5px\" ");
            
            #line 49 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Angular\NgListingComponentHtml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.IsOutgoingRefKey ? "" : "mat-sort-header"));
            
            #line default
            #line hidden
            this.Write(">\r\n\t\t\t\t\t");
            
            #line 50 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Angular\NgListingComponentHtml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.PropertyName));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t</th>\r\n\t\t\t\t<td mat-cell *matCellDef=\"let rowData\" style=\"padding: 5px\">\r\n\r\n" +
                    "\t\t\t\t\t\r\n\t\t\t\t\t<ng-container *ngTemplateOutlet=\"templates.");
            
            #line 55 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Angular\NgListingComponentHtml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.PropertyName.Lf()));
            
            #line default
            #line hidden
            this.Write("Template || default");
            
            #line 55 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Angular\NgListingComponentHtml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.PropertyName));
            
            #line default
            #line hidden
            this.Write("Template; context: { rowData: rowData }\"></ng-container>\r\n\r\n\t\t\t\t\t<ng-template #de" +
                    "fault");
            
            #line 57 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Angular\NgListingComponentHtml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.PropertyName));
            
            #line default
            #line hidden
            this.Write("Template>\r\n\r\n                        ");
            
            #line 59 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Angular\NgListingComponentHtml.tt"
 if(!col.IsOutgoingRefKey) { 
            
            #line default
            #line hidden
            this.Write("                        {{ rowData.");
            
            #line 60 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Angular\NgListingComponentHtml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.PropertyName.Lf()));
            
            #line default
            #line hidden
            this.Write(" }}\r\n                        ");
            
            #line 61 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Angular\NgListingComponentHtml.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("                        <!--\r\n                            You may also use below " +
                    "to open a new page to see details.\r\n                            - target=\"_blank" +
                    "\" and\r\n                            - [routerLink]=\"\'/");
            
            #line 65 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Angular\NgListingComponentHtml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.OutgoingReference.ParentTableMetadata.EntityName.Lf()));
            
            #line default
            #line hidden
            this.Write("/\' + rowData.");
            
            #line 65 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Angular\NgListingComponentHtml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.PropertyName.Lf()));
            
            #line default
            #line hidden
            this.Write(" + \'/edit\'\"\r\n                        -->\r\n                        <a mat-button\r\n" +
                    "                            (click)=\"show");
            
            #line 68 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Angular\NgListingComponentHtml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.OutgoingReference.ParentTableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write("Details(rowData.");
            
            #line 68 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Angular\NgListingComponentHtml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.PropertyName.Lf()));
            
            #line default
            #line hidden
            this.Write(")\">\r\n                            {{ rowData.");
            
            #line 69 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Angular\NgListingComponentHtml.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.PropertyName.Lf()));
            
            #line default
            #line hidden
            this.Write(" }}...\r\n                        </a>\r\n                        ");
            
            #line 71 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Angular\NgListingComponentHtml.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t\t</ng-template>\r\n\r\n\t\t\t\t\t\r\n\t\t\t\t</td>\r\n\t\t\t</ng-container>\r\n\t\t");
            
            #line 78 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Angular\NgListingComponentHtml.tt"
 } 
            
            #line default
            #line hidden
            this.Write(@"

			<ng-container matColumnDef=""actions"">
				<th mat-header-cell *matHeaderCellDef>
		
				</th>

				<td mat-cell *matCellDef=""let rowData"">
					<button mat-button (click)=""edit(rowData)"">
						<mat-icon>
							edit
						</mat-icon>
						Edit
					</button>

					<button mat-button (click)=""delete(rowData)"">
						<mat-icon>
							delete
						</mat-icon>
						Delete
					</button>
				</td>
			</ng-container>


			<tr mat-header-row *matHeaderRowDef=""displayedColumns""></tr>
			<tr mat-row *matRowDef=""let row; columns: displayedColumns;""></tr>
		</table>

		<mat-paginator [length]=""resultsLength"" [pageSizeOptions]=""[5, 10, 20, 50, 100]"" showFirstLastButtons></mat-paginator>
	</div>
</div>");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
