// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Tangsem.Generator.Templates.Repositories
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using Tangsem.Common.Extensions;
    using Tangsem.Generator.Templates;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryInterfaceTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class RepositoryInterfaceTemplate : Tangsem.Common.T4.T4TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\n");
            this.Write("\r\n\r\nusing System;\r\nusing System.Collections;\r\nusing System.Collections.Generic;\r\n" +
                    "using System.Text;\r\nusing System.Linq;\r\nusing System.Threading.Tasks;\r\nusing Sys" +
                    "tem.Linq.Expressions;\r\n\r\nusing Tangsem.Data.Domain;\r\n\r\n\r\nusing ");
            
            #line 22 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Configuration.EntityNamespace));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\n\r\nnamespace ");
            
            #line 25 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Configuration.RepositoryNamespace));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n\t/// <summary>\r\n\t/// The I");
            
            #line 28 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Configuration.RepositoryName));
            
            #line default
            #line hidden
            this.Write(" interface.\r\n\t/// </summary>\r\n\tpublic partial interface I");
            
            #line 30 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Configuration.RepositoryName));
            
            #line default
            #line hidden
            this.Write(" : IRepository\r\n\t{\r\n\r\n\t\t");
            
            #line 33 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryInterfaceTemplate.tt"
 foreach (var tableMetadata in this.TableMetadatas) { 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t/// <summary>\r\n\t\t/// Maps to database table/view ");
            
            #line 36 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.Name));
            
            #line default
            #line hidden
            this.Write(". The IQueryable for ");
            
            #line 36 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName.Pluralize()));
            
            #line default
            #line hidden
            this.Write(".\r\n\t\t/// </summary>\r\n\t\tIQueryable<");
            
            #line 38 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write("> ");
            
            #line 38 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName.Pluralize()));
            
            #line default
            #line hidden
            this.Write(" { get; }\r\n\t\r\n\t\t");
            
            #line 40 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryInterfaceTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\r\n\t\t\r\n\t\t");
            
            #line 43 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryInterfaceTemplate.tt"
 foreach (var tableMetadata in this.TableMetadatas.Where(x => !x.IsView)) { 
            
            #line default
            #line hidden
            this.Write("\t\t/// <summary>\r\n\t\t/// Get ");
            
            #line 45 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write(" by primary key.\r\n\t\t/// </summary>\r\n\t\t");
            
            #line 47 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write(" Lookup");
            
            #line 47 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write("By");
            
            #line 47 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.PrimaryKeys[0].PropertyName));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 47 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.PrimaryKeys[0].CSharpTypeAsString));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 47 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.PrimaryKeys[0].PropertyName.LowerFirst()));
            
            #line default
            #line hidden
            this.Write(");\r\n\r\n\t\t/// <summary>\r\n\t\t/// Get ");
            
            #line 50 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write(" by primary key.\r\n\t\t/// </summary>\r\n\t\tSystem.Threading.Tasks.Task<");
            
            #line 52 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write("> Lookup");
            
            #line 52 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write("By");
            
            #line 52 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.PrimaryKeys[0].PropertyName));
            
            #line default
            #line hidden
            this.Write("Async(");
            
            #line 52 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.PrimaryKeys[0].CSharpTypeAsString));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 52 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.PrimaryKeys[0].PropertyName.LowerFirst()));
            
            #line default
            #line hidden
            this.Write(");\r\n\r\n\t\t/// <summary>\r\n\t\t/// Delete ");
            
            #line 55 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write(" by primary key.\r\n\t\t/// </summary>\r\n\t\t");
            
            #line 57 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write(" Delete");
            
            #line 57 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write("By");
            
            #line 57 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.PrimaryKeys[0].PropertyName));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 57 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.PrimaryKeys[0].CSharpTypeAsString));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 57 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.PrimaryKeys[0].PropertyName.LowerFirst()));
            
            #line default
            #line hidden
            this.Write(");\r\n\t\t\r\n\t\t/// <summary>\r\n\t\t/// Delete ");
            
            #line 60 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write(" by primary key.\r\n\t\t/// </summary>\r\n\t\tSystem.Threading.Tasks.Task<");
            
            #line 62 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write("> Delete");
            
            #line 62 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write("By");
            
            #line 62 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.PrimaryKeys[0].PropertyName));
            
            #line default
            #line hidden
            this.Write("Async(");
            
            #line 62 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.PrimaryKeys[0].CSharpTypeAsString));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 62 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.PrimaryKeys[0].PropertyName.LowerFirst()));
            
            #line default
            #line hidden
            this.Write(");\r\n\t\t\r\n\t\t");
            
            #line 64 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryInterfaceTemplate.tt"
 foreach (var uniqueKey in tableMetadata.UniqueKeys.Where(x => !x.IsPrimaryKey))
		{
			var combinedKeyColumnNames = string.Join(", ", uniqueKey.Columns.Select(x => x.PropertyName));
			var combinedArguments = string.Join(", ", uniqueKey.Columns.Select(x => x.CSharpTypeAsString + " " + x.PropertyName.LowerFirst()));
			
            
            #line default
            #line hidden
            this.Write("\t\t#region ");
            
            #line 69 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(uniqueKey.Name));
            
            #line default
            #line hidden
            this.Write("\r\n\t\r\n\t\t/// <summary>\r\n\t\t/// Lookup ");
            
            #line 72 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write(" by ");
            
            #line 72 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(combinedKeyColumnNames));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t/// </summary>\r\n\t\t");
            
            #line 74 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write(" Lookup");
            
            #line 74 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write("By");
            
            #line 74 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(combinedKeyColumnNames));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 74 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(combinedArguments));
            
            #line default
            #line hidden
            this.Write(", System.Linq.Expressions.Expression<Func<");
            
            #line 74 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write(", bool>> extraFilter = null);\r\n\t\t\r\n\t\t/// <summary>\r\n\t\t/// Lookup ");
            
            #line 77 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write(" by ");
            
            #line 77 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(combinedKeyColumnNames));
            
            #line default
            #line hidden
            this.Write(" async\r\n\t\t/// </summary>\r\n\t\tSystem.Threading.Tasks.Task<");
            
            #line 79 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write("> Lookup");
            
            #line 79 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write("By");
            
            #line 79 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(combinedKeyColumnNames));
            
            #line default
            #line hidden
            this.Write("Async(");
            
            #line 79 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(combinedArguments));
            
            #line default
            #line hidden
            this.Write(", System.Linq.Expressions.Expression<Func<");
            
            #line 79 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write(", bool>> extraFilter = null);\r\n\t\t\r\n\t\t/// <summary>\r\n\t\t/// Deletes ");
            
            #line 82 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write(" by ");
            
            #line 82 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(combinedKeyColumnNames));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t/// </summary>\r\n\t\t");
            
            #line 84 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write(" Delete");
            
            #line 84 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write("By");
            
            #line 84 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(combinedKeyColumnNames));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 84 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(combinedArguments));
            
            #line default
            #line hidden
            this.Write(");\r\n\t\t\r\n\t\t/// <summary>\r\n\t\t/// Deletes ");
            
            #line 87 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write(" by ");
            
            #line 87 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(combinedKeyColumnNames));
            
            #line default
            #line hidden
            this.Write(" async.\r\n\t\t/// </summary>\r\n\t\tSystem.Threading.Tasks.Task<");
            
            #line 89 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write("> Delete");
            
            #line 89 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write("By");
            
            #line 89 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(combinedKeyColumnNames));
            
            #line default
            #line hidden
            this.Write("Async(");
            
            #line 89 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(combinedArguments));
            
            #line default
            #line hidden
            this.Write(");\r\n\r\n\t\t#endregion\r\n\t\t");
            
            #line 92 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryInterfaceTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t/// <summary>\r\n\t\t/// Save a new ");
            
            #line 95 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write(" instance.\r\n\t\t/// </summary>\r\n\t\t");
            
            #line 97 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write(" Save");
            
            #line 97 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 97 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 97 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName.LowerFirst()));
            
            #line default
            #line hidden
            this.Write(");\r\n    \r\n\t\t/// <summary>\r\n\t\t/// Save a new ");
            
            #line 100 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write(" instance.\r\n\t\t/// </summary>\r\n\t\tSystem.Threading.Tasks.Task<");
            
            #line 102 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write("> Save");
            
            #line 102 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write("Async(");
            
            #line 102 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 102 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName.LowerFirst()));
            
            #line default
            #line hidden
            this.Write(");\r\n\t\t\r\n\t\t/// <summary>\r\n\t\t/// Update an existing ");
            
            #line 105 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write(" instance.\r\n\t\t/// </summary>\r\n\t\t");
            
            #line 107 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write(" Update");
            
            #line 107 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 107 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 107 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName.LowerFirst()));
            
            #line default
            #line hidden
            this.Write(");\r\n\t\t\r\n\t\t/// <summary>\r\n\t\t/// Update an existing ");
            
            #line 110 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write(" instance.\r\n\t\t/// </summary>\r\n\t\tSystem.Threading.Tasks.Task<");
            
            #line 112 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write("> Update");
            
            #line 112 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write("Async(");
            
            #line 112 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 112 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName.LowerFirst()));
            
            #line default
            #line hidden
            this.Write(");\r\n\t\t\r\n\t\t/// <summary>\r\n\t\t/// Save or update an existing ");
            
            #line 115 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write(" instance.\r\n\t\t/// </summary>\r\n\t\t");
            
            #line 117 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write(" SaveOrUpdate");
            
            #line 117 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 117 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 117 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName.LowerFirst()));
            
            #line default
            #line hidden
            this.Write(");\r\n\r\n\t\t/// <summary>\r\n\t\t/// Save or update an existing ");
            
            #line 120 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write(" instance.\r\n\t\t/// </summary>\r\n\t\tSystem.Threading.Tasks.Task<");
            
            #line 122 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write("> SaveOrUpdate");
            
            #line 122 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write("Async(");
            
            #line 122 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 122 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName.LowerFirst()));
            
            #line default
            #line hidden
            this.Write(");\r\n\r\n\t\t");
            
            #line 124 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryInterfaceTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n\t}\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
