// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Tangsem.Generator.Templates.Repositories
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using Tangsem.Common.Extensions;
    using Tangsem.Generator.Templates;
    using Tangsem.Generator.Settings;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class RepositoryClassTemplate : Tangsem.Common.T4.T4TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\n");
            this.Write("\r\n\r\nusing System;\r\nusing System.Collections;\r\nusing System.Collections.Generic;\r\n" +
                    "using System.Text;\r\nusing System.Linq;\r\nusing System.Linq.Expressions;\r\nusing Sy" +
                    "stem.Threading.Tasks;\r\n\r\nusing Tangsem.Data.Domain;\r\nusing Tangsem.");
            
            #line 21 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Configuration.OrmType.AsNamespacePart()));
            
            #line default
            #line hidden
            this.Write(".Domain;\r\nusing ");
            
            #line 22 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Configuration.EntityNamespace));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\nusing NHibernate.Linq;\r\n\r\nnamespace ");
            
            #line 26 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Configuration.RepositoryNamespace));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 26 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Configuration.OrmType.AsNamespacePart()));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n  /// <summary>\r\n  /// The ");
            
            #line 29 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Configuration.RepositoryName));
            
            #line default
            #line hidden
            this.Write(" class.\r\n  /// </summary>\r\n  public partial class ");
            
            #line 31 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Configuration.RepositoryName));
            
            #line default
            #line hidden
            this.Write(" : ");
            
            #line 31 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Configuration.RepositoryBaseClassName ?? "RepositoryBase"));
            
            #line default
            #line hidden
            this.Write(", I");
            
            #line 31 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Configuration.RepositoryName));
            
            #line default
            #line hidden
            this.Write("\r\n  {\r\n    ");
            
            #line 33 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
 foreach (var tableMetadata in this.TableMetadatas) { 
            
            #line default
            #line hidden
            this.Write("  \r\n    /// <summary>\r\n    /// The IQueryable for ");
            
            #line 36 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName.Pluralize()));
            
            #line default
            #line hidden
            this.Write(".\r\n    /// </summary>\r\n    public virtual IQueryable<");
            
            #line 38 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write("> ");
            
            #line 38 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName.Pluralize()));
            
            #line default
            #line hidden
            this.Write("\r\n    {\r\n      get\r\n      {\r\n        return this.GetEntities<");
            
            #line 42 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write(">();\r\n      }\r\n    }\r\n    ");
            
            #line 45 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("    \r\n    \r\n    ");
            
            #line 48 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
 foreach (var tableMetadata in this.TableMetadatas.Where(x => !x.IsView)) { 
            
            #line default
            #line hidden
            this.Write("      \r\n    /// <summary>\r\n    /// Get ");
            
            #line 51 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write(" by primary key.\r\n    /// </summary>\r\n    public virtual ");
            
            #line 53 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write(" Lookup");
            
            #line 53 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write("By");
            
            #line 53 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.PrimaryKeys[0].PropertyName));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 53 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.PrimaryKeys[0].CSharpTypeAsString));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 53 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.PrimaryKeys[0].PropertyName.LowerFirst()));
            
            #line default
            #line hidden
            this.Write(")\r\n    {\r\n      return this.LookupById<");
            
            #line 55 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write(">(");
            
            #line 55 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.PrimaryKeys[0].PropertyName.LowerFirst()));
            
            #line default
            #line hidden
            this.Write(");\r\n    }\r\n    \r\n    /// <summary>\r\n    /// Get ");
            
            #line 59 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write(" by primary key.\r\n    /// </summary>\r\n    public virtual async Task<");
            
            #line 61 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write("> Lookup");
            
            #line 61 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write("By");
            
            #line 61 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.PrimaryKeys[0].PropertyName));
            
            #line default
            #line hidden
            this.Write("Async(");
            
            #line 61 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.PrimaryKeys[0].CSharpTypeAsString));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 61 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.PrimaryKeys[0].PropertyName.LowerFirst()));
            
            #line default
            #line hidden
            this.Write(")\r\n    {\r\n      return await this.LookupByIdAsync<");
            
            #line 63 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write(">(");
            
            #line 63 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.PrimaryKeys[0].PropertyName.LowerFirst()));
            
            #line default
            #line hidden
            this.Write(");\r\n    }\r\n    \r\n    /// <summary>\r\n    /// Delete ");
            
            #line 67 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write(" by primary key.\r\n    /// </summary>\r\n    public virtual ");
            
            #line 69 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write(" Delete");
            
            #line 69 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write("By");
            
            #line 69 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.PrimaryKeys[0].PropertyName));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 69 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.PrimaryKeys[0].CSharpTypeAsString));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 69 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.PrimaryKeys[0].PropertyName.LowerFirst()));
            
            #line default
            #line hidden
            this.Write(")\r\n    {\r\n      return this.DeleteById<");
            
            #line 71 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write(">(");
            
            #line 71 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.PrimaryKeys[0].PropertyName.LowerFirst()));
            
            #line default
            #line hidden
            this.Write(");\r\n    }\r\n    \r\n    /// <summary>\r\n    /// Delete ");
            
            #line 75 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write(" by primary key.\r\n    /// </summary>\r\n    public virtual async Task<");
            
            #line 77 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write("> Delete");
            
            #line 77 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write("By");
            
            #line 77 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.PrimaryKeys[0].PropertyName));
            
            #line default
            #line hidden
            this.Write("Async(");
            
            #line 77 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.PrimaryKeys[0].CSharpTypeAsString));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 77 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.PrimaryKeys[0].PropertyName.LowerFirst()));
            
            #line default
            #line hidden
            this.Write(")\r\n    {\r\n      return await this.DeleteByIdAsync<");
            
            #line 79 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write(">(");
            
            #line 79 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.PrimaryKeys[0].PropertyName.LowerFirst()));
            
            #line default
            #line hidden
            this.Write(");\r\n    }\r\n    \r\n    /// <summary>\r\n    /// Save a new ");
            
            #line 83 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write(" instance.\r\n    /// </summary>\r\n    public virtual ");
            
            #line 85 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write(" Save");
            
            #line 85 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 85 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 85 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName.LowerFirst()));
            
            #line default
            #line hidden
            this.Write(")\r\n    {\r\n      return this.Save<");
            
            #line 87 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write(">(");
            
            #line 87 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName.LowerFirst()));
            
            #line default
            #line hidden
            this.Write(");\r\n    }\r\n    \r\n    /// <summary>\r\n    /// Save a new ");
            
            #line 91 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write(" instance.\r\n    /// </summary>\r\n    public virtual async Task<");
            
            #line 93 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write("> Save");
            
            #line 93 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write("Async(");
            
            #line 93 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 93 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName.LowerFirst()));
            
            #line default
            #line hidden
            this.Write(")\r\n    {\r\n      return await this.SaveAsync<");
            
            #line 95 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write(">(");
            
            #line 95 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName.LowerFirst()));
            
            #line default
            #line hidden
            this.Write(");\r\n    }\r\n    \r\n    /// <summary>\r\n    /// Update an existing ");
            
            #line 99 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write(" instance.\r\n    /// </summary>\r\n    public virtual ");
            
            #line 101 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write(" Update");
            
            #line 101 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 101 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 101 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName.LowerFirst()));
            
            #line default
            #line hidden
            this.Write(")\r\n    {\r\n      return this.Update<");
            
            #line 103 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write(">(");
            
            #line 103 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName.LowerFirst()));
            
            #line default
            #line hidden
            this.Write(");\r\n    }\r\n    \r\n    /// <summary>\r\n    /// Update an existing ");
            
            #line 107 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write(" instance.\r\n    /// </summary>\r\n    public virtual async Task<");
            
            #line 109 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write("> Update");
            
            #line 109 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write("Async(");
            
            #line 109 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 109 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName.LowerFirst()));
            
            #line default
            #line hidden
            this.Write(")\r\n    {\r\n      return await this.UpdateAsync<");
            
            #line 111 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write(">(");
            
            #line 111 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName.LowerFirst()));
            
            #line default
            #line hidden
            this.Write(");\r\n    }\r\n    \r\n    /// <summary>\r\n    /// Save or update an existing ");
            
            #line 115 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write(" instance.\r\n    /// </summary>\r\n    public virtual ");
            
            #line 117 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write(" SaveOrUpdate");
            
            #line 117 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 117 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 117 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName.LowerFirst()));
            
            #line default
            #line hidden
            this.Write(")\r\n    {\r\n      return this.SaveOrUpdate<");
            
            #line 119 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write(">(");
            
            #line 119 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName.LowerFirst()));
            
            #line default
            #line hidden
            this.Write(");\r\n    }\r\n    \r\n    /// <summary>\r\n    /// Save or update an existing ");
            
            #line 123 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write(" instance.\r\n    /// </summary>\r\n    public virtual async Task<");
            
            #line 125 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write("> SaveOrUpdate");
            
            #line 125 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write("Async(");
            
            #line 125 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 125 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName.LowerFirst()));
            
            #line default
            #line hidden
            this.Write(")\r\n    {\r\n      return await this.SaveOrUpdateAsync<");
            
            #line 127 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write(">(");
            
            #line 127 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName.LowerFirst()));
            
            #line default
            #line hidden
            this.Write(");\r\n    }\r\n    \r\n    ");
            
            #line 130 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
 foreach (var uniqueKey in tableMetadata.UniqueKeys.Where(x => !x.IsPrimaryKey)) {
        var combinedKeyColumnNames = string.Join(", ", uniqueKey.Columns.Select(x => x.ColumnName));
        var combinedArguments = string.Join(", ", uniqueKey.Columns.Select(x => x.CSharpTypeAsString + " " + x.PropertyName.LowerFirst()));
        var combinedArgumentValues = string.Join(", ", uniqueKey.Columns.Select(x => x.PropertyName.LowerFirst()));
        var whereCondExpr = string.Join(" && ", uniqueKey.Columns.Select(x => "x." + x.PropertyName + " == " + x.PropertyName.LowerFirst()));
	  
            
            #line default
            #line hidden
            this.Write("    #region ");
            
            #line 136 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(uniqueKey.Name));
            
            #line default
            #line hidden
            this.Write("\r\n    \r\n    /// <summary>\r\n    /// Lookup ");
            
            #line 139 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write(" by ");
            
            #line 139 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(combinedKeyColumnNames));
            
            #line default
            #line hidden
            this.Write("\r\n    /// </summary>\r\n    public virtual ");
            
            #line 141 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write(" Lookup");
            
            #line 141 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write("By");
            
            #line 141 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(combinedKeyColumnNames));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 141 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(combinedArguments));
            
            #line default
            #line hidden
            this.Write(", System.Linq.Expressions.Expression<Func<");
            
            #line 141 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write(", bool>> extraFilter = null)\r\n    {\r\n      var qry = this.");
            
            #line 143 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName.Pluralize()));
            
            #line default
            #line hidden
            this.Write(";\r\n      if (extraFilter != null)\r\n      {\r\n        qry = qry.Where(extraFilter);" +
                    "\r\n      }\r\n\r\n      return qry.FirstOrDefault(x => ");
            
            #line 149 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(whereCondExpr));
            
            #line default
            #line hidden
            this.Write(");\r\n    }\r\n    \r\n    /// <summary>\r\n    /// Lookup ");
            
            #line 153 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write(" by ");
            
            #line 153 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(combinedKeyColumnNames));
            
            #line default
            #line hidden
            this.Write(" async\r\n    /// </summary>\r\n    public async System.Threading.Tasks.Task<");
            
            #line 155 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write("> Lookup");
            
            #line 155 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write("By");
            
            #line 155 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(combinedKeyColumnNames));
            
            #line default
            #line hidden
            this.Write("Async(");
            
            #line 155 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(combinedArguments));
            
            #line default
            #line hidden
            this.Write(", System.Linq.Expressions.Expression<Func<");
            
            #line 155 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write(", bool>> extraFilter = null)\r\n    {\r\n      var qry = this.");
            
            #line 157 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName.Pluralize()));
            
            #line default
            #line hidden
            this.Write(";\r\n      if (extraFilter != null)\r\n      {\r\n        qry = qry.Where(extraFilter);" +
                    "\r\n      }\r\n\r\n      return await qry.FirstOrDefaultAsync(x => ");
            
            #line 163 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(whereCondExpr));
            
            #line default
            #line hidden
            this.Write(");\r\n    }\r\n    \r\n    /// <summary>\r\n    /// Deletes ");
            
            #line 167 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write(" by ");
            
            #line 167 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(combinedKeyColumnNames));
            
            #line default
            #line hidden
            this.Write("\r\n    /// </summary>\r\n    public ");
            
            #line 169 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write(" Delete");
            
            #line 169 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write("By");
            
            #line 169 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(combinedKeyColumnNames));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 169 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(combinedArguments));
            
            #line default
            #line hidden
            this.Write(")\r\n    {\r\n      var entity = this.Lookup");
            
            #line 171 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write("By");
            
            #line 171 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(combinedKeyColumnNames));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 171 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(combinedArgumentValues));
            
            #line default
            #line hidden
            this.Write(");\r\n      if (entity != null)\r\n      {\r\n        this.Delete(entity);\r\n      }\r\n  " +
                    "  \r\n      return entity;\r\n    }\r\n\r\n    /// <summary>\r\n    /// Deletes ");
            
            #line 181 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write(" by ");
            
            #line 181 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(combinedKeyColumnNames));
            
            #line default
            #line hidden
            this.Write(" async.\r\n    /// </summary>\r\n    public async System.Threading.Tasks.Task<");
            
            #line 183 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write("> Delete");
            
            #line 183 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write("By");
            
            #line 183 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(combinedKeyColumnNames));
            
            #line default
            #line hidden
            this.Write("Async(");
            
            #line 183 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(combinedArguments));
            
            #line default
            #line hidden
            this.Write(")\r\n    {\r\n      var entity = await this.Lookup");
            
            #line 185 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write("By");
            
            #line 185 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(combinedKeyColumnNames));
            
            #line default
            #line hidden
            this.Write("Async(");
            
            #line 185 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(combinedArgumentValues));
            
            #line default
            #line hidden
            this.Write(");\r\n      if (entity != null)\r\n      {\r\n        await this.DeleteAsync(entity);\r\n" +
                    "      }\r\n      \r\n      return entity;\r\n    }\r\n\r\n    #endregion\r\n  ");
            
            #line 195 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n  \r\n\r\n  ");
            
            #line 199 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\Repositories\RepositoryClassTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("  }\r\n}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
