#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.530
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tangsem.Generator.Templates.Repositories
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 4 "..\..\Templates\Repositories\Repository.NHibernate.Designer.cshtml"
    using Tangsem.Common.Extensions;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Templates\Repositories\Repository.NHibernate.Designer.cshtml"
    using Tangsem.Generator.Templates;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.3.2.0")]
    public partial class Repository_NHibernate_Designer : MultipleTableMetadataTemplate
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");


WriteLiteral("\t\t\t  \r\n");



WriteLiteral("\r\nusing System;\r\nusing System.Collections;\r\nusing System.Collections.Generic;\r\nus" +
"ing System.Text;\r\nusing System.Linq;\r\nusing System.Linq.Expressions;\r\n\r\nusing Ta" +
"ngsem.Data.Domain;\r\nusing Tangsem.NHibernate.Domain;\r\n\r\nusing ");


            
            #line 17 "..\..\Templates\Repositories\Repository.NHibernate.Designer.cshtml"
  Write(Configuration.EntityNamespace);

            
            #line default
            #line hidden
WriteLiteral(";\r\n\r\nnamespace ");


            
            #line 19 "..\..\Templates\Repositories\Repository.NHibernate.Designer.cshtml"
      Write(Configuration.RepositoryNamespace);

            
            #line default
            #line hidden
WriteLiteral("\r\n{\r\n\t/// <summary>\r\n\t/// The ");


            
            #line 22 "..\..\Templates\Repositories\Repository.NHibernate.Designer.cshtml"
     Write(Configuration.RepositoryName);

            
            #line default
            #line hidden
WriteLiteral(" class.\r\n\t/// </summary>\r\n\tpublic partial class ");


            
            #line 24 "..\..\Templates\Repositories\Repository.NHibernate.Designer.cshtml"
                  Write(Configuration.RepositoryName);

            
            #line default
            #line hidden
WriteLiteral(" : RepositoryBase, I");


            
            #line 24 "..\..\Templates\Repositories\Repository.NHibernate.Designer.cshtml"
                                                                     Write(Configuration.RepositoryName);

            
            #line default
            #line hidden
WriteLiteral("\r\n\t{\r\n");


            
            #line 26 "..\..\Templates\Repositories\Repository.NHibernate.Designer.cshtml"
 		foreach (var tableMetadata in this.TableMetadatas)
		{
            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\r\n\t\t/// <summary>\r\n\t\t/// The IQueryable for ");


            
            #line 30 "..\..\Templates\Repositories\Repository.NHibernate.Designer.cshtml"
                     Write(tableMetadata.EntityName.Pluralize());

            
            #line default
            #line hidden
WriteLiteral(".\r\n\t\t/// </summary>\r\n\t\tpublic virtual IQueryable<");


            
            #line 32 "..\..\Templates\Repositories\Repository.NHibernate.Designer.cshtml"
                        Write(tableMetadata.EntityName);

            
            #line default
            #line hidden
WriteLiteral("> ");


            
            #line 32 "..\..\Templates\Repositories\Repository.NHibernate.Designer.cshtml"
                                                     Write(tableMetadata.EntityName.Pluralize());

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t{\r\n\t\t\tget\r\n\t\t\t{\r\n\t\t\t\treturn this.GetEntities<");


            
            #line 36 "..\..\Templates\Repositories\Repository.NHibernate.Designer.cshtml"
                        Write(tableMetadata.EntityName);

            
            #line default
            #line hidden
WriteLiteral(">();\r\n\t\t\t}\r\n\t\t}\r\n\r\n\t\t");


            
            #line 40 "..\..\Templates\Repositories\Repository.NHibernate.Designer.cshtml"
         }

            
            #line default
            #line hidden
WriteLiteral("\t\t\r\n\t\t\r\n");


            
            #line 43 "..\..\Templates\Repositories\Repository.NHibernate.Designer.cshtml"
 		foreach (var tableMetadata in this.TableMetadatas.Where(x => !x.IsView))
		{
            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\r\n\t\t/// <summary>\r\n\t\t/// Get ");


            
            #line 47 "..\..\Templates\Repositories\Repository.NHibernate.Designer.cshtml"
      Write(tableMetadata.EntityName);

            
            #line default
            #line hidden
WriteLiteral(" by primary key.\r\n\t\t/// </summary>\r\n\t\tpublic virtual ");


            
            #line 49 "..\..\Templates\Repositories\Repository.NHibernate.Designer.cshtml"
             Write(tableMetadata.EntityName);

            
            #line default
            #line hidden
WriteLiteral(" Lookup");


            
            #line 49 "..\..\Templates\Repositories\Repository.NHibernate.Designer.cshtml"
                                               Write(tableMetadata.EntityName);

            
            #line default
            #line hidden
WriteLiteral("By");


            
            #line 49 "..\..\Templates\Repositories\Repository.NHibernate.Designer.cshtml"
                                                                            Write(tableMetadata.PrimaryKeys[0].PropertyName);

            
            #line default
            #line hidden
WriteLiteral("(");


            
            #line 49 "..\..\Templates\Repositories\Repository.NHibernate.Designer.cshtml"
                                                                                                                         Write(tableMetadata.PrimaryKeys[0].CSharpTypeAsString);

            
            #line default
            #line hidden
WriteLiteral(" ");


            
            #line 49 "..\..\Templates\Repositories\Repository.NHibernate.Designer.cshtml"
                                                                                                                                                                            Write(tableMetadata.PrimaryKeys[0].PropertyName.LowerFirst());

            
            #line default
            #line hidden
WriteLiteral(")\r\n\t\t{\r\n\t\t\treturn this.LookupById<");


            
            #line 51 "..\..\Templates\Repositories\Repository.NHibernate.Designer.cshtml"
                      Write(tableMetadata.EntityName);

            
            #line default
            #line hidden
WriteLiteral(">(");


            
            #line 51 "..\..\Templates\Repositories\Repository.NHibernate.Designer.cshtml"
                                                   Write(tableMetadata.PrimaryKeys[0].PropertyName.LowerFirst());

            
            #line default
            #line hidden
WriteLiteral(");\r\n\t\t}\r\n\t\t\r\n\t\t/// <summary>\r\n\t\t/// Delete ");


            
            #line 55 "..\..\Templates\Repositories\Repository.NHibernate.Designer.cshtml"
         Write(tableMetadata.EntityName);

            
            #line default
            #line hidden
WriteLiteral(" by primary key.\r\n\t\t/// </summary>\r\n\t\tpublic virtual ");


            
            #line 57 "..\..\Templates\Repositories\Repository.NHibernate.Designer.cshtml"
             Write(tableMetadata.EntityName);

            
            #line default
            #line hidden
WriteLiteral(" Delete");


            
            #line 57 "..\..\Templates\Repositories\Repository.NHibernate.Designer.cshtml"
                                               Write(tableMetadata.EntityName);

            
            #line default
            #line hidden
WriteLiteral("By");


            
            #line 57 "..\..\Templates\Repositories\Repository.NHibernate.Designer.cshtml"
                                                                            Write(tableMetadata.PrimaryKeys[0].PropertyName);

            
            #line default
            #line hidden
WriteLiteral("(");


            
            #line 57 "..\..\Templates\Repositories\Repository.NHibernate.Designer.cshtml"
                                                                                                                         Write(tableMetadata.PrimaryKeys[0].CSharpTypeAsString);

            
            #line default
            #line hidden
WriteLiteral(" ");


            
            #line 57 "..\..\Templates\Repositories\Repository.NHibernate.Designer.cshtml"
                                                                                                                                                                            Write(tableMetadata.PrimaryKeys[0].PropertyName.LowerFirst());

            
            #line default
            #line hidden
WriteLiteral(")\r\n\t\t{\r\n\t\t\treturn this.DeleteById<");


            
            #line 59 "..\..\Templates\Repositories\Repository.NHibernate.Designer.cshtml"
                      Write(tableMetadata.EntityName);

            
            #line default
            #line hidden
WriteLiteral(">(");


            
            #line 59 "..\..\Templates\Repositories\Repository.NHibernate.Designer.cshtml"
                                                   Write(tableMetadata.PrimaryKeys[0].PropertyName.LowerFirst());

            
            #line default
            #line hidden
WriteLiteral(");\r\n\t\t}\r\n\t\t\r\n\t\t/// <summary>\r\n\t\t/// Save a new ");


            
            #line 63 "..\..\Templates\Repositories\Repository.NHibernate.Designer.cshtml"
             Write(tableMetadata.EntityName);

            
            #line default
            #line hidden
WriteLiteral(" instance.\r\n\t\t/// </summary>\r\n\t\tpublic virtual ");


            
            #line 65 "..\..\Templates\Repositories\Repository.NHibernate.Designer.cshtml"
             Write(tableMetadata.EntityName);

            
            #line default
            #line hidden
WriteLiteral(" Save");


            
            #line 65 "..\..\Templates\Repositories\Repository.NHibernate.Designer.cshtml"
                                             Write(tableMetadata.EntityName);

            
            #line default
            #line hidden
WriteLiteral("(");


            
            #line 65 "..\..\Templates\Repositories\Repository.NHibernate.Designer.cshtml"
                                                                         Write(tableMetadata.EntityName);

            
            #line default
            #line hidden
WriteLiteral(" ");


            
            #line 65 "..\..\Templates\Repositories\Repository.NHibernate.Designer.cshtml"
                                                                                                     Write(tableMetadata.EntityName.LowerFirst());

            
            #line default
            #line hidden
WriteLiteral(")\r\n\t\t{\r\n\t\t\treturn this.Save<");


            
            #line 67 "..\..\Templates\Repositories\Repository.NHibernate.Designer.cshtml"
                Write(tableMetadata.EntityName);

            
            #line default
            #line hidden
WriteLiteral(">(");


            
            #line 67 "..\..\Templates\Repositories\Repository.NHibernate.Designer.cshtml"
                                             Write(tableMetadata.EntityName.LowerFirst());

            
            #line default
            #line hidden
WriteLiteral(");\r\n\t\t}\r\n\t\t\r\n\t\t/// <summary>\r\n\t\t/// Update an existing ");


            
            #line 71 "..\..\Templates\Repositories\Repository.NHibernate.Designer.cshtml"
                     Write(tableMetadata.EntityName);

            
            #line default
            #line hidden
WriteLiteral(" instance.\r\n\t\t/// </summary>\r\n\t\tpublic virtual ");


            
            #line 73 "..\..\Templates\Repositories\Repository.NHibernate.Designer.cshtml"
             Write(tableMetadata.EntityName);

            
            #line default
            #line hidden
WriteLiteral(" Update");


            
            #line 73 "..\..\Templates\Repositories\Repository.NHibernate.Designer.cshtml"
                                               Write(tableMetadata.EntityName);

            
            #line default
            #line hidden
WriteLiteral("(");


            
            #line 73 "..\..\Templates\Repositories\Repository.NHibernate.Designer.cshtml"
                                                                           Write(tableMetadata.EntityName);

            
            #line default
            #line hidden
WriteLiteral(" ");


            
            #line 73 "..\..\Templates\Repositories\Repository.NHibernate.Designer.cshtml"
                                                                                                       Write(tableMetadata.EntityName.LowerFirst());

            
            #line default
            #line hidden
WriteLiteral(")\r\n\t\t{\r\n\t\t\treturn this.Update<");


            
            #line 75 "..\..\Templates\Repositories\Repository.NHibernate.Designer.cshtml"
                  Write(tableMetadata.EntityName);

            
            #line default
            #line hidden
WriteLiteral(">(");


            
            #line 75 "..\..\Templates\Repositories\Repository.NHibernate.Designer.cshtml"
                                               Write(tableMetadata.EntityName.LowerFirst());

            
            #line default
            #line hidden
WriteLiteral(");\r\n\t\t}\r\n\t\t\r\n\t\t/// <summary>\r\n\t\t/// Save or update an existing ");


            
            #line 79 "..\..\Templates\Repositories\Repository.NHibernate.Designer.cshtml"
                             Write(tableMetadata.EntityName);

            
            #line default
            #line hidden
WriteLiteral(" instance.\r\n\t\t/// </summary>\r\n\t\tpublic virtual ");


            
            #line 81 "..\..\Templates\Repositories\Repository.NHibernate.Designer.cshtml"
             Write(tableMetadata.EntityName);

            
            #line default
            #line hidden
WriteLiteral(" SaveOrUpdate");


            
            #line 81 "..\..\Templates\Repositories\Repository.NHibernate.Designer.cshtml"
                                                     Write(tableMetadata.EntityName);

            
            #line default
            #line hidden
WriteLiteral("(");


            
            #line 81 "..\..\Templates\Repositories\Repository.NHibernate.Designer.cshtml"
                                                                                 Write(tableMetadata.EntityName);

            
            #line default
            #line hidden
WriteLiteral(" ");


            
            #line 81 "..\..\Templates\Repositories\Repository.NHibernate.Designer.cshtml"
                                                                                                             Write(tableMetadata.EntityName.LowerFirst());

            
            #line default
            #line hidden
WriteLiteral(")\r\n\t\t{\r\n\t\t\treturn this.SaveOrUpdate<");


            
            #line 83 "..\..\Templates\Repositories\Repository.NHibernate.Designer.cshtml"
                        Write(tableMetadata.EntityName);

            
            #line default
            #line hidden
WriteLiteral(">(");


            
            #line 83 "..\..\Templates\Repositories\Repository.NHibernate.Designer.cshtml"
                                                     Write(tableMetadata.EntityName.LowerFirst());

            
            #line default
            #line hidden
WriteLiteral(");\r\n\t\t}\r\n\r\n\t\t");


            
            #line 86 "..\..\Templates\Repositories\Repository.NHibernate.Designer.cshtml"
         }

            
            #line default
            #line hidden
WriteLiteral("\r\n\t}\r\n}\r\n");


            
            #line 90 "..\..\Templates\Repositories\Repository.NHibernate.Designer.cshtml"
  
  var plainEntities = this.TableMetadatas.Where(x => !x.IsAuditableEntity && !x.IsView).ToList();


            
            #line default
            #line hidden

            
            #line 93 "..\..\Templates\Repositories\Repository.NHibernate.Designer.cshtml"
 if(plainEntities.Any())
{
            
            #line default
            #line hidden
WriteLiteral("\r\n/*    \r\n  ");


WriteLiteral("@NOTE: The following entities are not IAuditableEntities:\r\n     \r\n");


            
            #line 98 "..\..\Templates\Repositories\Repository.NHibernate.Designer.cshtml"
   foreach(var entity in plainEntities)
  {
            
            #line default
            #line hidden
WriteLiteral("\r\n     \r\n  ------------------------------\r\n  -- ");


            
            #line 102 "..\..\Templates\Repositories\Repository.NHibernate.Designer.cshtml"
Write(entity.EntityName);

            
            #line default
            #line hidden
WriteLiteral("     ----\r\n  ------------------------------\r\n  ALTER TABLE ");


            
            #line 104 "..\..\Templates\Repositories\Repository.NHibernate.Designer.cshtml"
         Write(entity.Name);

            
            #line default
            #line hidden
WriteLiteral(" ADD CreatedById INT NULL\r\n  GO\r\n  ALTER TABLE ");


            
            #line 106 "..\..\Templates\Repositories\Repository.NHibernate.Designer.cshtml"
         Write(entity.Name);

            
            #line default
            #line hidden
WriteLiteral(" ADD ModifiedById INT NULL\r\n  GO\r\n  ALTER TABLE ");


            
            #line 108 "..\..\Templates\Repositories\Repository.NHibernate.Designer.cshtml"
         Write(entity.Name);

            
            #line default
            #line hidden
WriteLiteral(" ADD CreatedTime DATETIME NULL\r\n  GO\r\n  ALTER TABLE ");


            
            #line 110 "..\..\Templates\Repositories\Repository.NHibernate.Designer.cshtml"
         Write(entity.Name);

            
            #line default
            #line hidden
WriteLiteral(" ADD ModifiedTime DATETIME NULL\r\n  GO\r\n  ALTER TABLE ");


            
            #line 112 "..\..\Templates\Repositories\Repository.NHibernate.Designer.cshtml"
         Write(entity.Name);

            
            #line default
            #line hidden
WriteLiteral(" ADD Active BIT NULL\r\n  GO\r\n         \r\n       \r\n  ");


            
            #line 116 "..\..\Templates\Repositories\Repository.NHibernate.Designer.cshtml"
         }

            
            #line default
            #line hidden
WriteLiteral("*/\r\n");


            
            #line 118 "..\..\Templates\Repositories\Repository.NHibernate.Designer.cshtml"
       }

            
            #line default
            #line hidden
WriteLiteral("\r\n");


        }
    }
}
#pragma warning restore 1591
