#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.431
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tangsem.Generator.Templates.Entities
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 3 "..\..\Templates\Entities\Poco.NHibernate.Fluent.Designer.cshtml"
    using Tangsem.Generator.Metadata;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Templates\Entities\Poco.NHibernate.Fluent.Designer.cshtml"
    using Tangsem.Generator.Settings;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.3.2.0")]
    public partial class Poco_NHibernate_Fluent_Designer : RazorGenerator.Templating.RazorTemplateBase
    {
#line hidden

        #line 6 "..\..\Templates\Entities\Poco.NHibernate.Fluent.Designer.cshtml"


	/// <summary>
	/// The table metadata.
	/// </summary>
	public TableMetadata TableMetadata { get; set; }

	/// <summary>
	/// The generator configuration instance.
	/// </summary>
	public GeneratorConfiguration Configuration { get; set; }


        #line default
        #line hidden

        public override void Execute()
        {


WriteLiteral("\r\n\r\n");



WriteLiteral("\r\n");


WriteLiteral("\r\n\r\nusing System;\r\nusing System.Collections;\r\nusing System.Collections.Generic;\r\n" +
"using System.Text;\r\nusing System.Linq;\r\n\r\nusing FluentNHibernate.Mapping;\r\n\r\nnam" +
"espace ");


            
            #line 28 "..\..\Templates\Entities\Poco.NHibernate.Fluent.Designer.cshtml"
      Write(Configuration.MappingNamespace);

            
            #line default
            #line hidden
WriteLiteral("\r\n{\r\n\t/// <summary>\r\n\t/// The mapping configuration for ");


            
            #line 31 "..\..\Templates\Entities\Poco.NHibernate.Fluent.Designer.cshtml"
                               Write(TableMetadata.EntityName);

            
            #line default
            #line hidden
WriteLiteral(".\r\n\t/// </summary>\r\n\tpublic partial class ");


            
            #line 33 "..\..\Templates\Entities\Poco.NHibernate.Fluent.Designer.cshtml"
                  Write(TableMetadata.EntityName);

            
            #line default
            #line hidden
WriteLiteral("Map : ClassMap<");


            
            #line 33 "..\..\Templates\Entities\Poco.NHibernate.Fluent.Designer.cshtml"
                                                            Write(TableMetadata.EntityName);

            
            #line default
            #line hidden
WriteLiteral(">\r\n\t{\r\n\t\t/// <summary>\r\n\t\t/// The constructor.\r\n\t\t/// </summary>\r\n\t\tpublic ");


            
            #line 38 "..\..\Templates\Entities\Poco.NHibernate.Fluent.Designer.cshtml"
     Write(TableMetadata.EntityName);

            
            #line default
            #line hidden
WriteLiteral(@"Map()
		{
			// primary key mapping
			this.MapId();
			
			// basic columns mapping
			this.MapBasicColumns();
			
			// outgoing references mapping
			this.MapOutgoingReferences();
			
			// incoming references mapping
			this.MapIncomingReferences();
		}
		
		/// <summary>
		/// Map the Primary Key.
		/// </summary>
		private void MapId()
		{
			this.Id(x => x.");


            
            #line 58 "..\..\Templates\Entities\Poco.NHibernate.Fluent.Designer.cshtml"
              Write(TableMetadata.PrimaryKeys[0].PropertyName);

            
            #line default
            #line hidden
WriteLiteral(")\r\n\t\t\t\t.Column(\"");


            
            #line 59 "..\..\Templates\Entities\Poco.NHibernate.Fluent.Designer.cshtml"
         Write(TableMetadata.PrimaryKeys[0].ColumnName);

            
            #line default
            #line hidden
WriteLiteral("\")\r\n\t\t\t\t.GeneratedBy\r\n\t\t\t\t.Native();\r\n\t\t}\r\n\t\t\r\n\t\t/// <summary>\r\n\t\t/// Map the Bas" +
"ic Columns.\r\n\t\t/// </summary>\r\n\t\tprivate void MapBasicColumns()\r\n\t\t{\r\n");


            
            #line 69 "..\..\Templates\Entities\Poco.NHibernate.Fluent.Designer.cshtml"
 			foreach (var col in @TableMetadata.Columns.Where(c => !c.IsOutgoingRefKey && !c.IsPrimaryKey))
			{
            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\tthis.Map(x => x.");


            
            #line 71 "..\..\Templates\Entities\Poco.NHibernate.Fluent.Designer.cshtml"
               Write(col.PropertyName);

            
            #line default
            #line hidden
WriteLiteral(")\r\n                .Column(\"");


            
            #line 72 "..\..\Templates\Entities\Poco.NHibernate.Fluent.Designer.cshtml"
                     Write(col.ColumnName);

            
            #line default
            #line hidden

            
            #line 72 "..\..\Templates\Entities\Poco.NHibernate.Fluent.Designer.cshtml"
                                          WriteLiteral("\")");

            
            #line default
            #line hidden
            
            #line 72 "..\..\Templates\Entities\Poco.NHibernate.Fluent.Designer.cshtml"
                                             if (col.Nullable) {
            
            #line default
            #line hidden
WriteLiteral(";");


            
            #line 72 "..\..\Templates\Entities\Poco.NHibernate.Fluent.Designer.cshtml"
                                                                              }else{
            
            #line default
            #line hidden
WriteLiteral(".Not.Nullable();");


            
            #line 72 "..\..\Templates\Entities\Poco.NHibernate.Fluent.Designer.cshtml"
                                                                                                                 }

            
            #line default
            #line hidden
WriteLiteral("\t\t\t");


            
            #line 73 "..\..\Templates\Entities\Poco.NHibernate.Fluent.Designer.cshtml"
          }

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t}\r\n\t\t\r\n\t\t/// <summary>\r\n\t\t/// Map the Outgoing References.\r\n\t\t/// </summary>\r" +
"\n\t\tprivate void MapOutgoingReferences()\r\n\t\t{\r\n");


            
            #line 82 "..\..\Templates\Entities\Poco.NHibernate.Fluent.Designer.cshtml"
 			foreach (var reference in this.TableMetadata.OutgoingReferences)
			{
            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\tthis.References<");


            
            #line 84 "..\..\Templates\Entities\Poco.NHibernate.Fluent.Designer.cshtml"
               Write(reference.ParentTableMetadata.EntityName);

            
            #line default
            #line hidden
WriteLiteral(">(x => x.");


            
            #line 84 "..\..\Templates\Entities\Poco.NHibernate.Fluent.Designer.cshtml"
                                                                   Write(reference.ParentPropertyName);

            
            #line default
            #line hidden
WriteLiteral(")\r\n                .Fetch.Join()\r\n                .Column(\"");


            
            #line 86 "..\..\Templates\Entities\Poco.NHibernate.Fluent.Designer.cshtml"
                     Write(reference.ColumnPairs[0].ChildColumnMetadata.ColumnName);

            
            #line default
            #line hidden

            
            #line 86 "..\..\Templates\Entities\Poco.NHibernate.Fluent.Designer.cshtml"
                                                                                   WriteLiteral("\")");

            
            #line default
            #line hidden
            
            #line 86 "..\..\Templates\Entities\Poco.NHibernate.Fluent.Designer.cshtml"
                                                                                      if (reference.ColumnPairs[0].ChildColumnMetadata.Nullable){
            
            #line default
            #line hidden
WriteLiteral(";");


            
            #line 86 "..\..\Templates\Entities\Poco.NHibernate.Fluent.Designer.cshtml"
                                                                                                                                                               }else{
            
            #line default
            #line hidden
WriteLiteral(".Not.Nullable();");


            
            #line 86 "..\..\Templates\Entities\Poco.NHibernate.Fluent.Designer.cshtml"
                                                                                                                                                                                                  }

            
            #line default
            #line hidden
WriteLiteral("\t\t\t");


            
            #line 87 "..\..\Templates\Entities\Poco.NHibernate.Fluent.Designer.cshtml"
          }

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t}\r\n\t\t\r\n\t\t/// <summary>\r\n\t\t/// Map the Incoming References.\r\n\t\t/// </summary>\r" +
"\n\t\tprivate void MapIncomingReferences()\r\n\t\t{\r\n");


            
            #line 96 "..\..\Templates\Entities\Poco.NHibernate.Fluent.Designer.cshtml"
 			foreach (var reference in this.TableMetadata.IncomingReferences)
			{
            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\tthis.HasMany<");


            
            #line 98 "..\..\Templates\Entities\Poco.NHibernate.Fluent.Designer.cshtml"
            Write(reference.ChildTableMetadata.EntityName);

            
            #line default
            #line hidden
WriteLiteral(">(x => x.");


            
            #line 98 "..\..\Templates\Entities\Poco.NHibernate.Fluent.Designer.cshtml"
                                                               Write(reference.ChildListPropertyName);

            
            #line default
            #line hidden
WriteLiteral(")\r\n\t\t\t\t.KeyColumn(\"");


            
            #line 99 "..\..\Templates\Entities\Poco.NHibernate.Fluent.Designer.cshtml"
            Write(reference.ColumnPairs[0].ChildColumnMetadata.ColumnName);

            
            #line default
            #line hidden
WriteLiteral("\")\r\n                .Inverse()\r\n                .LazyLoad()\r\n                .AsB" +
"ag();\r\n\t\t\t");


            
            #line 103 "..\..\Templates\Entities\Poco.NHibernate.Fluent.Designer.cshtml"
          }

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t}\r\n\t}\r\n}");


        }
    }
}
#pragma warning restore 1591
