#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    
    #line 4 "..\..\Templates\Entities\Poco.EF.Fluent.Designer.cshtml"
    using System.Linq;
    
    #line default
    #line hidden
    using System.Text;
    
    #line 5 "..\..\Templates\Entities\Poco.EF.Fluent.Designer.cshtml"
    using Tangsem.Generator.Metadata;
    
    #line default
    #line hidden
    
    #line 6 "..\..\Templates\Entities\Poco.EF.Fluent.Designer.cshtml"
    using Tangsem.Generator.Settings;
    
    #line default
    #line hidden
    
    #line 7 "..\..\Templates\Entities\Poco.EF.Fluent.Designer.cshtml"
    using Tangsem.Generator.Templates;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class _Templates_Entities_Poco_EF_Fluent_Designer_cshtml : SingleTableMetadataTemplate
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");


WriteLiteral("        \r\n");





WriteLiteral("\r\nusing System;\r\nusing System.Collections;\r\nusing System.Collections.Generic;\r\nus" +
"ing System.Text;\r\nusing System.Linq;\r\nusing System.Data.Entity;\r\n\r\nusing Tangsem" +
".EF.Mappings;\r\n/* http://msdn.microsoft.com/en-us/library/hh295843(v=vs.103) */\r" +
"\nnamespace ");


            
            #line 18 "..\..\Templates\Entities\Poco.EF.Fluent.Designer.cshtml"
      Write(Configuration.MappingNamespace);

            
            #line default
            #line hidden
WriteLiteral("\r\n{\r\n  /// <summary>\r\n  /// The mapping configuration for ");


            
            #line 21 "..\..\Templates\Entities\Poco.EF.Fluent.Designer.cshtml"
                                Write(TableMetadata.EntityName);

            
            #line default
            #line hidden
WriteLiteral(".\r\n  /// </summary>\r\n  public partial class ");


            
            #line 23 "..\..\Templates\Entities\Poco.EF.Fluent.Designer.cshtml"
                   Write(TableMetadata.EntityName);

            
            #line default
            #line hidden
WriteLiteral("Map : ClassMap<");


            
            #line 23 "..\..\Templates\Entities\Poco.EF.Fluent.Designer.cshtml"
                                                             Write(TableMetadata.EntityName);

            
            #line default
            #line hidden
WriteLiteral(">\r\n  {\r\n    /// <summary>\r\n    /// The constructor.\r\n    /// </summary>\r\n    publ" +
"ic ");


            
            #line 28 "..\..\Templates\Entities\Poco.EF.Fluent.Designer.cshtml"
       Write(TableMetadata.EntityName);

            
            #line default
            #line hidden
WriteLiteral("Map() : base()\r\n    {\r\n    }\r\n    \r\n    /// <summary>\r\n    /// Map Table.\r\n    //" +
"/ </summary>\r\n    protected override void MapTable(DbModelBuilder modelBuilder)\r" +
"\n    {\r\n      this.EntityTypeConfiguration.ToTable(\"");


            
            #line 37 "..\..\Templates\Entities\Poco.EF.Fluent.Designer.cshtml"
                                        Write(TableMetadata.Name);

            
            #line default
            #line hidden
WriteLiteral("\");\r\n    }\r\n\r\n    /// <summary>\r\n    /// Map the Primary Key.\r\n    /// </summary>" +
"\r\n    protected override void MapId(DbModelBuilder modelBuilder)\r\n    {\r\n");


            
            #line 45 "..\..\Templates\Entities\Poco.EF.Fluent.Designer.cshtml"
     if(TableMetadata.PrimaryKeys.Any())
    {
            
            #line default
            #line hidden
WriteLiteral("\r\n        this.EntityTypeConfiguration\r\n            .HasKey(x => x.");


            
            #line 48 "..\..\Templates\Entities\Poco.EF.Fluent.Designer.cshtml"
                       Write(TableMetadata.PrimaryKeys[0].PropertyName);

            
            #line default
            #line hidden
WriteLiteral(")\r\n            .Property(x => x.");


            
            #line 49 "..\..\Templates\Entities\Poco.EF.Fluent.Designer.cshtml"
                         Write(TableMetadata.PrimaryKeys[0].PropertyName);

            
            #line default
            #line hidden
WriteLiteral(")\r\n            .HasColumnName(\"");


            
            #line 50 "..\..\Templates\Entities\Poco.EF.Fluent.Designer.cshtml"
                        Write(TableMetadata.PrimaryKeys[0].ColumnName);

            
            #line default
            #line hidden
WriteLiteral("\");\r\n    ");


            
            #line 51 "..\..\Templates\Entities\Poco.EF.Fluent.Designer.cshtml"
           }

            
            #line default
            #line hidden
WriteLiteral("    }\r\n    \r\n    /// <summary>\r\n    /// Map the Basic Columns.\r\n    /// </summary" +
">\r\n    protected override void MapBasicColumns(DbModelBuilder modelBuilder)\r\n   " +
" {\r\n");


            
            #line 59 "..\..\Templates\Entities\Poco.EF.Fluent.Designer.cshtml"
       foreach (var col in @TableMetadata.Columns.Where(c => (!c.IsOutgoingRefKey || !Configuration.GenRelationship) && !c.IsPrimaryKey))
      {
            
            #line default
            #line hidden
WriteLiteral("\r\n         this.EntityTypeConfiguration\r\n             .Property(x => x.");


            
            #line 62 "..\..\Templates\Entities\Poco.EF.Fluent.Designer.cshtml"
                          Write(col.PropertyName);

            
            #line default
            #line hidden
WriteLiteral(")\r\n             .HasColumnName(\"");


            
            #line 63 "..\..\Templates\Entities\Poco.EF.Fluent.Designer.cshtml"
                         Write(col.ColumnName);

            
            #line default
            #line hidden

            
            #line 63 "..\..\Templates\Entities\Poco.EF.Fluent.Designer.cshtml"
                                              WriteLiteral("\")");

            
            #line default
            #line hidden
            
            #line 63 "..\..\Templates\Entities\Poco.EF.Fluent.Designer.cshtml"
                                                 if (col.Nullable) {
            
            #line default
            #line hidden
WriteLiteral(";");


            
            #line 63 "..\..\Templates\Entities\Poco.EF.Fluent.Designer.cshtml"
                                                                                  }else{
            
            #line default
            #line hidden
WriteLiteral(".IsRequired();");


            
            #line 63 "..\..\Templates\Entities\Poco.EF.Fluent.Designer.cshtml"
                                                                                                                   }

            
            #line default
            #line hidden
WriteLiteral("      ");


            
            #line 64 "..\..\Templates\Entities\Poco.EF.Fluent.Designer.cshtml"
             }

            
            #line default
            #line hidden
WriteLiteral("\r\n    }\r\n    \r\n    /// <summary>\r\n    /// Map the MapRelationships.\r\n    /// </su" +
"mmary>\r\n    protected override void MapRelationships(DbModelBuilder modelBuilder" +
")\r\n    {\r\n");


            
            #line 73 "..\..\Templates\Entities\Poco.EF.Fluent.Designer.cshtml"
       if (Configuration.GenRelationship) {
        foreach (var reference in this.TableMetadata.OutgoingReferences)
        {
          var optional = reference.ColumnPairs[0].ChildColumnMetadata.Nullable;

            
            #line default
            #line hidden
WriteLiteral("        ");

WriteLiteral("\r\n          this.EntityTypeConfiguration\r\n              .Has");


            
            #line 79 "..\..\Templates\Entities\Poco.EF.Fluent.Designer.cshtml"
              Write(optional ? "Optional" : "Required");

            
            #line default
            #line hidden
WriteLiteral("(x => x.");


            
            #line 79 "..\..\Templates\Entities\Poco.EF.Fluent.Designer.cshtml"
                                                           Write(reference.ParentPropertyName);

            
            #line default
            #line hidden
WriteLiteral(")\r\n          .WithMany(x => x.");


            
            #line 80 "..\..\Templates\Entities\Poco.EF.Fluent.Designer.cshtml"
                       Write(reference.ChildListPropertyName);

            
            #line default
            #line hidden
WriteLiteral(")\r\n          .Map(m => m.MapKey(\"");


            
            #line 81 "..\..\Templates\Entities\Poco.EF.Fluent.Designer.cshtml"
                          Write(reference.ColumnPairs[0].ChildColumnMetadata.ColumnName);

            
            #line default
            #line hidden
WriteLiteral("\"));\r\n        ");

WriteLiteral("\r\n");


            
            #line 83 "..\..\Templates\Entities\Poco.EF.Fluent.Designer.cshtml"
        }
      }

            
            #line default
            #line hidden
WriteLiteral("    }\r\n  }\r\n}");


        }
    }
}
#pragma warning restore 1591
