#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    
    #line 4 "..\..\Templates\Entities\Poco.NHibernate.Fluent.Designer.cshtml"
    using System.Linq;
    
    #line default
    #line hidden
    using System.Text;
    
    #line 5 "..\..\Templates\Entities\Poco.NHibernate.Fluent.Designer.cshtml"
    using Tangsem.Generator.Metadata;
    
    #line default
    #line hidden
    
    #line 6 "..\..\Templates\Entities\Poco.NHibernate.Fluent.Designer.cshtml"
    using Tangsem.Generator.Settings;
    
    #line default
    #line hidden
    
    #line 7 "..\..\Templates\Entities\Poco.NHibernate.Fluent.Designer.cshtml"
    using Tangsem.Generator.Templates;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class _Templates_Entities_Poco_NHibernate_Fluent_Designer_cshtml : SingleTableMetadataTemplate
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");


WriteLiteral("\t\t\t  \r\n");





WriteLiteral("\r\nusing System;\r\nusing System.Collections;\r\nusing System.Collections.Generic;\r\nus" +
"ing System.Text;\r\nusing System.Linq;\r\n\r\nusing FluentNHibernate.Mapping;\r\n\r\nusing" +
" Tangsem.NHibernate.UserTypes;\r\n\r\nnamespace ");


            
            #line 19 "..\..\Templates\Entities\Poco.NHibernate.Fluent.Designer.cshtml"
      Write(Configuration.MappingNamespace);

            
            #line default
            #line hidden
WriteLiteral("\r\n{\r\n\t/// <summary>\r\n\t/// The mapping configuration for ");


            
            #line 22 "..\..\Templates\Entities\Poco.NHibernate.Fluent.Designer.cshtml"
                               Write(TableMetadata.EntityName);

            
            #line default
            #line hidden
WriteLiteral(".\r\n\t/// </summary>\r\n\tpublic partial class ");


            
            #line 24 "..\..\Templates\Entities\Poco.NHibernate.Fluent.Designer.cshtml"
                  Write(TableMetadata.EntityName);

            
            #line default
            #line hidden
WriteLiteral("Map : ClassMap<");


            
            #line 24 "..\..\Templates\Entities\Poco.NHibernate.Fluent.Designer.cshtml"
                                                            Write(TableMetadata.EntityName);

            
            #line default
            #line hidden
WriteLiteral(">\r\n\t{\r\n\t\t/// <summary>\r\n\t\t/// The constructor.\r\n\t\t/// </summary>\r\n\t\tpublic ");


            
            #line 29 "..\..\Templates\Entities\Poco.NHibernate.Fluent.Designer.cshtml"
     Write(TableMetadata.EntityName);

            
            #line default
            #line hidden

            
            #line 29 "..\..\Templates\Entities\Poco.NHibernate.Fluent.Designer.cshtml"
                                    WriteLiteral("Map()\r\n    {");

            
            #line default
            #line hidden
            
            #line 30 "..\..\Templates\Entities\Poco.NHibernate.Fluent.Designer.cshtml"
      if (TableMetadata.Schema != "dbo")
      {
            
            #line default
            #line hidden
WriteLiteral("\r\n      this.Schema(\"");


            
            #line 32 "..\..\Templates\Entities\Poco.NHibernate.Fluent.Designer.cshtml"
               Write(TableMetadata.Schema);

            
            #line default
            #line hidden
WriteLiteral("\");\r\n      ");


            
            #line 33 "..\..\Templates\Entities\Poco.NHibernate.Fluent.Designer.cshtml"
             }

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\tthis.Table(\"[");


            
            #line 35 "..\..\Templates\Entities\Poco.NHibernate.Fluent.Designer.cshtml"
            Write(TableMetadata.Name);

            
            #line default
            #line hidden
WriteLiteral("]\");\r\n\t\t\t\r\n");


            
            #line 37 "..\..\Templates\Entities\Poco.NHibernate.Fluent.Designer.cshtml"
 			if(TableMetadata.IsView)
			{
            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\tthis.ReadOnly();\r\n\t\t\t");


            
            #line 40 "..\..\Templates\Entities\Poco.NHibernate.Fluent.Designer.cshtml"
          }

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t// primary key mapping\r\n\t\t\tthis.MapId();\r\n\t\t\t\r\n\t\t\t// basic columns mapping\r\n" +
"\t\t\tthis.MapBasicColumns();\r\n\t\t\t\r\n");


            
            #line 48 "..\..\Templates\Entities\Poco.NHibernate.Fluent.Designer.cshtml"
       if (Configuration.GenRelationship) {
            
            #line default
            #line hidden
WriteLiteral("\r\n      // outgoing references mapping\r\n\t\t\tthis.MapOutgoingReferences();\r\n\t\t\t\r\n\t\t" +
"\t// incoming references mapping\r\n      this.MapIncomingReferences();\r\n      ");


            
            #line 54 "..\..\Templates\Entities\Poco.NHibernate.Fluent.Designer.cshtml"
             }

            
            #line default
            #line hidden
WriteLiteral("\t\t}\r\n\t\t\r\n\t\t/// <summary>\r\n\t\t/// Map the Primary Key.\r\n\t\t/// </summary>\r\n\t\tprivate" +
" void MapId()\r\n\t\t{\r\n");


            
            #line 62 "..\..\Templates\Entities\Poco.NHibernate.Fluent.Designer.cshtml"
 			if (TableMetadata.PrimaryKeys.Any(x => x.IsAutoIncrement))
			{
            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\tthis.Id(x => x.");


            
            #line 64 "..\..\Templates\Entities\Poco.NHibernate.Fluent.Designer.cshtml"
              Write(TableMetadata.PrimaryKeys[0].PropertyName);

            
            #line default
            #line hidden
WriteLiteral(")\r\n\t\t\t\t.Column(\"");


            
            #line 65 "..\..\Templates\Entities\Poco.NHibernate.Fluent.Designer.cshtml"
         Write(TableMetadata.PrimaryKeys[0].ColumnName);

            
            #line default
            #line hidden
WriteLiteral("\")\r\n\t\t\t\t.GeneratedBy\r\n\t\t\t\t.Native();\r\n\t\t\t");


            
            #line 68 "..\..\Templates\Entities\Poco.NHibernate.Fluent.Designer.cshtml"
          }
			else if (TableMetadata.PrimaryKeys.Count == 1)
      {
            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\tthis.Id(x => x.");


            
            #line 71 "..\..\Templates\Entities\Poco.NHibernate.Fluent.Designer.cshtml"
              Write(TableMetadata.PrimaryKeys[0].PropertyName);

            
            #line default
            #line hidden
WriteLiteral(")\r\n\t\t\t    .Column(\"");


            
            #line 72 "..\..\Templates\Entities\Poco.NHibernate.Fluent.Designer.cshtml"
            Write(TableMetadata.PrimaryKeys[0].ColumnName);

            
            #line default
            #line hidden
WriteLiteral("\");\t\r\n\t\t\t");


            
            #line 73 "..\..\Templates\Entities\Poco.NHibernate.Fluent.Designer.cshtml"
          }
      else if (TableMetadata.PrimaryKeys.Count == 0)
      {
            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\tthis.Id(x => x.");


            
            #line 76 "..\..\Templates\Entities\Poco.NHibernate.Fluent.Designer.cshtml"
              Write(TableMetadata.Columns[0].PropertyName);

            
            #line default
            #line hidden
WriteLiteral(")\r\n\t\t\t    .Column(\"");


            
            #line 77 "..\..\Templates\Entities\Poco.NHibernate.Fluent.Designer.cshtml"
            Write(TableMetadata.Columns[0].ColumnName);

            
            #line default
            #line hidden
WriteLiteral("\");\t\r\n\t\t\t");


            
            #line 78 "..\..\Templates\Entities\Poco.NHibernate.Fluent.Designer.cshtml"
          }
      else
      {

            
            #line default
            #line hidden
WriteLiteral("        ");

WriteLiteral("this.CompositeId()");

WriteLiteral("\r\n");


            
            #line 82 "..\..\Templates\Entities\Poco.NHibernate.Fluent.Designer.cshtml"
        foreach (var col in this.TableMetadata.PrimaryKeys)
        {

            
            #line default
            #line hidden
WriteLiteral("          ");

WriteLiteral(".KeyProperty(x => x.");


            
            #line 84 "..\..\Templates\Entities\Poco.NHibernate.Fluent.Designer.cshtml"
                                Write(col.PropertyName);

            
            #line default
            #line hidden
WriteLiteral(", \"");


            
            #line 84 "..\..\Templates\Entities\Poco.NHibernate.Fluent.Designer.cshtml"
                                                      Write(col.ColumnName);

            
            #line default
            #line hidden
WriteLiteral("\")");

WriteLiteral("\r\n");


            
            #line 85 "..\..\Templates\Entities\Poco.NHibernate.Fluent.Designer.cshtml"
        }
            
            #line default
            #line hidden
WriteLiteral(";");

WriteLiteral("\r\n");


            
            #line 86 "..\..\Templates\Entities\Poco.NHibernate.Fluent.Designer.cshtml"
      }

            
            #line default
            #line hidden
WriteLiteral("\t\t  \r\n\t\t}\r\n\t\t\r\n\t\t/// <summary>\r\n\t\t/// Map the Basic Columns.\r\n\t\t/// </summary>\r\n\t" +
"\tprivate void MapBasicColumns()\r\n\t\t{\r\n");


            
            #line 95 "..\..\Templates\Entities\Poco.NHibernate.Fluent.Designer.cshtml"
 			foreach (var col in @TableMetadata.Columns.Where(c => (!c.IsOutgoingRefKey || !Configuration.GenRelationship ) && !c.IsPrimaryKey))
			{
            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t   \r\n\t\t\t   // ");


            
            #line 98 "..\..\Templates\Entities\Poco.NHibernate.Fluent.Designer.cshtml"
     Write(col.ColumnName);

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 99 "..\..\Templates\Entities\Poco.NHibernate.Fluent.Designer.cshtml"
        if(col.ExtraColumnMeta == null || string.IsNullOrWhiteSpace(col.ExtraColumnMeta.JsonType))
       {
            
            #line default
            #line hidden
WriteLiteral("\r\n         \r\n         this.Map(x => x.");


            
            #line 102 "..\..\Templates\Entities\Poco.NHibernate.Fluent.Designer.cshtml"
                     Write(col.PropertyName);

            
            #line default
            #line hidden
WriteLiteral(").Column(\"");


            
            #line 102 "..\..\Templates\Entities\Poco.NHibernate.Fluent.Designer.cshtml"
                                                  Write(col.ColumnName);

            
            #line default
            #line hidden
WriteLiteral("\")\r\n\r\n");


            
            #line 104 "..\..\Templates\Entities\Poco.NHibernate.Fluent.Designer.cshtml"
          if (col.ClrType == typeof(string)) {
            
            #line default
            #line hidden
WriteLiteral(" ");

WriteLiteral(".Length(");


            
            #line 104 "..\..\Templates\Entities\Poco.NHibernate.Fluent.Designer.cshtml"
                                                         Write(col.ColumnSize > 0 ? col.ColumnSize.ToString() : "int.MaxValue");

            
            #line default
            #line hidden
WriteLiteral(")");

WriteLiteral(" ");


            
            #line 104 "..\..\Templates\Entities\Poco.NHibernate.Fluent.Designer.cshtml"
                                                                                                                                        }

            
            #line default
            #line hidden

            
            #line 105 "..\..\Templates\Entities\Poco.NHibernate.Fluent.Designer.cshtml"
          if (!col.Nullable) {
            
            #line default
            #line hidden
WriteLiteral(" ");

WriteLiteral(".Not.Nullable()");


            
            #line 105 "..\..\Templates\Entities\Poco.NHibernate.Fluent.Designer.cshtml"
                                                           }

            
            #line default
            #line hidden

            
            #line 106 "..\..\Templates\Entities\Poco.NHibernate.Fluent.Designer.cshtml"
          if (col.ReadOnly){
            
            #line default
            #line hidden
WriteLiteral(" ");

WriteLiteral(".ReadOnly()");


            
            #line 106 "..\..\Templates\Entities\Poco.NHibernate.Fluent.Designer.cshtml"
                                                     }
            
            #line default
            #line hidden
WriteLiteral(";\r\n        ");


            
            #line 107 "..\..\Templates\Entities\Poco.NHibernate.Fluent.Designer.cshtml"
               }
       else
       {

            
            #line default
            #line hidden
WriteLiteral("         ");

WriteLiteral("\r\n         this.Map(x => x.");


            
            #line 111 "..\..\Templates\Entities\Poco.NHibernate.Fluent.Designer.cshtml"
                     Write(col.PropertyName);

            
            #line default
            #line hidden
WriteLiteral(").Column(\"");


            
            #line 111 "..\..\Templates\Entities\Poco.NHibernate.Fluent.Designer.cshtml"
                                                  Write(col.ColumnName);

            
            #line default
            #line hidden
WriteLiteral("\").CustomType<JsonType<");


            
            #line 111 "..\..\Templates\Entities\Poco.NHibernate.Fluent.Designer.cshtml"
                                                                                         Write(col.ExtraColumnMeta.JsonType);

            
            #line default
            #line hidden
WriteLiteral(">>()\r\n");


            
            #line 112 "..\..\Templates\Entities\Poco.NHibernate.Fluent.Designer.cshtml"
          if (!col.Nullable) {
            
            #line default
            #line hidden
WriteLiteral(" ");

WriteLiteral(".Not.Nullable()");


            
            #line 112 "..\..\Templates\Entities\Poco.NHibernate.Fluent.Designer.cshtml"
                                                           }

            
            #line default
            #line hidden

            
            #line 113 "..\..\Templates\Entities\Poco.NHibernate.Fluent.Designer.cshtml"
          if (col.ReadOnly){
            
            #line default
            #line hidden
WriteLiteral(" ");

WriteLiteral(".ReadOnly()");


            
            #line 113 "..\..\Templates\Entities\Poco.NHibernate.Fluent.Designer.cshtml"
                                                     }
            
            #line default
            #line hidden
WriteLiteral(";\r\n        ");


            
            #line 114 "..\..\Templates\Entities\Poco.NHibernate.Fluent.Designer.cshtml"
               }

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t ");


            
            #line 116 "..\..\Templates\Entities\Poco.NHibernate.Fluent.Designer.cshtml"
           }

            
            #line default
            #line hidden
WriteLiteral("\t\t}\r\n\r\n");


            
            #line 119 "..\..\Templates\Entities\Poco.NHibernate.Fluent.Designer.cshtml"
     if (Configuration.GenRelationship) {
            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\r\n    /// <summary>\r\n\t\t/// Map the Outgoing References.\r\n\t\t/// </summary>\r\n\t\t" +
"private void MapOutgoingReferences()\r\n\t\t{\r\n");


            
            #line 126 "..\..\Templates\Entities\Poco.NHibernate.Fluent.Designer.cshtml"
 			foreach (var reference in this.TableMetadata.OutgoingReferences)
			{
            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\tthis.References<");


            
            #line 128 "..\..\Templates\Entities\Poco.NHibernate.Fluent.Designer.cshtml"
               Write(reference.ParentTableMetadata.EntityName);

            
            #line default
            #line hidden
WriteLiteral(">(x => x.");


            
            #line 128 "..\..\Templates\Entities\Poco.NHibernate.Fluent.Designer.cshtml"
                                                                   Write(reference.ParentPropertyName);

            
            #line default
            #line hidden
WriteLiteral(")\r\n                .Fetch.Join()\r\n                .Column(\"");


            
            #line 130 "..\..\Templates\Entities\Poco.NHibernate.Fluent.Designer.cshtml"
                     Write(reference.ColumnPairs[0].ChildColumnMetadata.ColumnName);

            
            #line default
            #line hidden

            
            #line 130 "..\..\Templates\Entities\Poco.NHibernate.Fluent.Designer.cshtml"
                                                                                   WriteLiteral("\")");

            
            #line default
            #line hidden
            
            #line 130 "..\..\Templates\Entities\Poco.NHibernate.Fluent.Designer.cshtml"
                                                                                      if (reference.ColumnPairs[0].ChildColumnMetadata.Nullable){
            
            #line default
            #line hidden
WriteLiteral(";");


            
            #line 130 "..\..\Templates\Entities\Poco.NHibernate.Fluent.Designer.cshtml"
                                                                                                                                                               }else{
            
            #line default
            #line hidden
WriteLiteral(".Not.Nullable();");


            
            #line 130 "..\..\Templates\Entities\Poco.NHibernate.Fluent.Designer.cshtml"
                                                                                                                                                                                                  }

            
            #line default
            #line hidden
WriteLiteral("\t\t\t");


            
            #line 131 "..\..\Templates\Entities\Poco.NHibernate.Fluent.Designer.cshtml"
          }

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t}\r\n\t\t\r\n\t\t/// <summary>\r\n\t\t/// Map the Incoming References.\r\n\t\t/// </summary>\r" +
"\n\t\tprivate void MapIncomingReferences()\r\n\t\t{\r\n");


            
            #line 140 "..\..\Templates\Entities\Poco.NHibernate.Fluent.Designer.cshtml"
 			foreach (var reference in this.TableMetadata.IncomingReferences)
			{
            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\tthis.HasMany<");


            
            #line 142 "..\..\Templates\Entities\Poco.NHibernate.Fluent.Designer.cshtml"
            Write(reference.ChildTableMetadata.EntityName);

            
            #line default
            #line hidden
WriteLiteral(">(x => x.");


            
            #line 142 "..\..\Templates\Entities\Poco.NHibernate.Fluent.Designer.cshtml"
                                                               Write(reference.ChildListPropertyName);

            
            #line default
            #line hidden
WriteLiteral(")\r\n\t\t\t\t.KeyColumn(\"");


            
            #line 143 "..\..\Templates\Entities\Poco.NHibernate.Fluent.Designer.cshtml"
            Write(reference.ColumnPairs[0].ChildColumnMetadata.ColumnName);

            
            #line default
            #line hidden
WriteLiteral("\")\r\n                .Inverse()\r\n                .LazyLoad()\r\n                .AsB" +
"ag();\r\n\t\t\t");


            
            #line 147 "..\..\Templates\Entities\Poco.NHibernate.Fluent.Designer.cshtml"
          }

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t}\r\n    ");


            
            #line 150 "..\..\Templates\Entities\Poco.NHibernate.Fluent.Designer.cshtml"
           }

            
            #line default
            #line hidden
WriteLiteral("\t}\r\n}");


        }
    }
}
#pragma warning restore 1591
