#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.431
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tangsem.Generator.Templates.Entities
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 4 "..\..\Templates\Entities\Poco.NHibernate.Designer.cshtml"
    using Tangsem.Generator.Metadata;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Templates\Entities\Poco.NHibernate.Designer.cshtml"
    using Tangsem.Generator.Settings;
    
    #line default
    #line hidden
    
    #line 6 "..\..\Templates\Entities\Poco.NHibernate.Designer.cshtml"
    using Tangsem.Generator.Templates;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.3.2.0")]
    public partial class Poco_NHibernate_Designer : SingleTableMetadataTemplate
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");


WriteLiteral("\r\n");




WriteLiteral("\r\nusing System;\r\nusing System.Collections;\r\nusing System.Collections.Generic;\r\nus" +
"ing System.Text;\r\nusing System.Linq;\r\nusing System.Linq.Expressions;\r\n\r\nnamespac" +
"e ");


            
            #line 15 "..\..\Templates\Entities\Poco.NHibernate.Designer.cshtml"
     Write(Configuration.EntityNamespace);

            
            #line default
            #line hidden
WriteLiteral("\r\n{\r\n\tpublic partial class ");


            
            #line 17 "..\..\Templates\Entities\Poco.NHibernate.Designer.cshtml"
                 Write(TableMetadata.EntityName);

            
            #line default
            #line hidden
WriteLiteral("\r\n\t{\r\n");


            
            #line 19 "..\..\Templates\Entities\Poco.NHibernate.Designer.cshtml"
 		foreach (var col in @TableMetadata.Columns.Where(c => !c.IsOutgoingRefKey))
		{
            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t/// <summary>\r\n\t\t/// The property name \'");


            
            #line 22 "..\..\Templates\Entities\Poco.NHibernate.Designer.cshtml"
                    Write(col.PropertyName);

            
            #line default
            #line hidden
WriteLiteral("\'. It matches the property to column \'");


            
            #line 22 "..\..\Templates\Entities\Poco.NHibernate.Designer.cshtml"
                                                                           Write(col.ColumnName);

            
            #line default
            #line hidden
WriteLiteral("\'.\r\n\t\t/// </summary>\r\n\t\tpublic static readonly string Prop_");


            
            #line 24 "..\..\Templates\Entities\Poco.NHibernate.Designer.cshtml"
                                 Write(col.PropertyName);

            
            #line default
            #line hidden
WriteLiteral(" = \"");


            
            #line 24 "..\..\Templates\Entities\Poco.NHibernate.Designer.cshtml"
                                                       Write(col.PropertyName);

            
            #line default
            #line hidden
WriteLiteral("\";\r\n\t\t\r\n\t\t/// <summary>\r\n\t\t/// The lamda expression for ");


            
            #line 27 "..\..\Templates\Entities\Poco.NHibernate.Designer.cshtml"
                          Write(col.PropertyName);

            
            #line default
            #line hidden
WriteLiteral(".\r\n\t\t/// </summary>\r\n\t\tpublic static readonly Expression<Func<");


            
            #line 29 "..\..\Templates\Entities\Poco.NHibernate.Designer.cshtml"
                                    Write(TableMetadata.EntityName);

            
            #line default
            #line hidden
WriteLiteral(", object>> Expr_");


            
            #line 29 "..\..\Templates\Entities\Poco.NHibernate.Designer.cshtml"
                                                                              Write(col.PropertyName);

            
            #line default
            #line hidden
WriteLiteral(" = x => x.");


            
            #line 29 "..\..\Templates\Entities\Poco.NHibernate.Designer.cshtml"
                                                                                                           Write(col.PropertyName);

            
            #line default
            #line hidden
WriteLiteral(";\r\n\t\t");


            
            #line 30 "..\..\Templates\Entities\Poco.NHibernate.Designer.cshtml"
         }

            
            #line default
            #line hidden
WriteLiteral("\t\t\r\n\t\t\r\n");


            
            #line 33 "..\..\Templates\Entities\Poco.NHibernate.Designer.cshtml"
 		foreach (var reference in this.TableMetadata.OutgoingReferences)
		{
            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t/// <summary>\r\n\t\t/// The property name \'");


            
            #line 36 "..\..\Templates\Entities\Poco.NHibernate.Designer.cshtml"
                     Write(reference.ParentPropertyName);

            
            #line default
            #line hidden
WriteLiteral("\'. It is for the reference \'");


            
            #line 36 "..\..\Templates\Entities\Poco.NHibernate.Designer.cshtml"
                                                                                Write(reference.Name);

            
            #line default
            #line hidden
WriteLiteral("\'.\r\n\t\t/// </summary>\r\n\t\tpublic static readonly string Prop_");


            
            #line 38 "..\..\Templates\Entities\Poco.NHibernate.Designer.cshtml"
                                 Write(reference.ParentPropertyName);

            
            #line default
            #line hidden
WriteLiteral("  = \"");


            
            #line 38 "..\..\Templates\Entities\Poco.NHibernate.Designer.cshtml"
                                                                     Write(reference.ParentPropertyName);

            
            #line default
            #line hidden
WriteLiteral("\";\r\n\r\n\t\t/// <summary>\r\n\t\t/// The lamda expression for ");


            
            #line 41 "..\..\Templates\Entities\Poco.NHibernate.Designer.cshtml"
                           Write(reference.ParentPropertyName);

            
            #line default
            #line hidden
WriteLiteral(".\r\n\t\t/// </summary>\r\n\t\tpublic static readonly Expression<Func<");


            
            #line 43 "..\..\Templates\Entities\Poco.NHibernate.Designer.cshtml"
                                     Write(this.TableMetadata.EntityName);

            
            #line default
            #line hidden
WriteLiteral(", object>> Expr_");


            
            #line 43 "..\..\Templates\Entities\Poco.NHibernate.Designer.cshtml"
                                                                                     Write(reference.ParentPropertyName);

            
            #line default
            #line hidden
WriteLiteral(" = x => x.");


            
            #line 43 "..\..\Templates\Entities\Poco.NHibernate.Designer.cshtml"
                                                                                                                              Write(reference.ParentPropertyName);

            
            #line default
            #line hidden
WriteLiteral(";\r\n\t\t");


            
            #line 44 "..\..\Templates\Entities\Poco.NHibernate.Designer.cshtml"
         }

            
            #line default
            #line hidden
WriteLiteral("\t\t\r\n\t\t\r\n\t\t/// <summary>\r\n\t\t/// The default constructor for ");


            
            #line 48 "..\..\Templates\Entities\Poco.NHibernate.Designer.cshtml"
                              Write(TableMetadata.EntityName);

            
            #line default
            #line hidden
WriteLiteral(" class.\r\n\t\t/// </summary>\r\n\t\tpublic ");


            
            #line 50 "..\..\Templates\Entities\Poco.NHibernate.Designer.cshtml"
     Write(TableMetadata.EntityName);

            
            #line default
            #line hidden
WriteLiteral("()\r\n\t\t{\r\n");


            
            #line 52 "..\..\Templates\Entities\Poco.NHibernate.Designer.cshtml"
 			foreach (var reference in this.TableMetadata.IncomingReferences)
			{
            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\tthis.");


            
            #line 54 "..\..\Templates\Entities\Poco.NHibernate.Designer.cshtml"
    Write(reference.ChildListPropertyName);

            
            #line default
            #line hidden
WriteLiteral(" = new List<");


            
            #line 54 "..\..\Templates\Entities\Poco.NHibernate.Designer.cshtml"
                                                  Write(reference.ChildTableMetadata.EntityName);

            
            #line default
            #line hidden
WriteLiteral(">();\r\n\t\t\t");


            
            #line 55 "..\..\Templates\Entities\Poco.NHibernate.Designer.cshtml"
          }

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t}\r\n\r\n\r\n\t\t#region \"Basic Columns\"\r\n\r\n");


            
            #line 62 "..\..\Templates\Entities\Poco.NHibernate.Designer.cshtml"
 		foreach (var col in @TableMetadata.Columns.Where(c => !c.IsOutgoingRefKey))
		{
            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t/// <summary>\r\n\t\t/// Property ");


            
            #line 65 "..\..\Templates\Entities\Poco.NHibernate.Designer.cshtml"
          Write(col.PropertyName);

            
            #line default
            #line hidden
WriteLiteral(" mapping to ");


            
            #line 65 "..\..\Templates\Entities\Poco.NHibernate.Designer.cshtml"
                                        Write(TableMetadata.Name);

            
            #line default
            #line hidden
WriteLiteral(".");


            
            #line 65 "..\..\Templates\Entities\Poco.NHibernate.Designer.cshtml"
                                                              Write(col.ColumnName);

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t/// </summary>\r\n\t\tpublic virtual ");


            
            #line 67 "..\..\Templates\Entities\Poco.NHibernate.Designer.cshtml"
            Write(col.CSharpTypeAsString);

            
            #line default
            #line hidden
WriteLiteral(" ");


            
            #line 67 "..\..\Templates\Entities\Poco.NHibernate.Designer.cshtml"
                                    Write(col.PropertyName);

            
            #line default
            #line hidden
WriteLiteral(" { get; set; }\r\n\t\t");


            
            #line 68 "..\..\Templates\Entities\Poco.NHibernate.Designer.cshtml"
         }

            
            #line default
            #line hidden
WriteLiteral("\t\t\r\n\t\t#endregion\r\n\t\t\r\n\t\t#region \"Outgoing References\"\r\n\t\t\r\n");


            
            #line 74 "..\..\Templates\Entities\Poco.NHibernate.Designer.cshtml"
 		foreach (var reference in @TableMetadata.OutgoingReferences)
		{
            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t/// <summary>\r\n\t\t/// Gets or sets reference to ");


            
            #line 77 "..\..\Templates\Entities\Poco.NHibernate.Designer.cshtml"
                            Write(reference.ParentPropertyName);

            
            #line default
            #line hidden
WriteLiteral(". ReferenceName: ");


            
            #line 77 "..\..\Templates\Entities\Poco.NHibernate.Designer.cshtml"
                                                                            Write(reference.Name);

            
            #line default
            #line hidden
WriteLiteral(".\r\n\t\t/// </summary>\r\n\t\tpublic virtual ");


            
            #line 79 "..\..\Templates\Entities\Poco.NHibernate.Designer.cshtml"
             Write(reference.ParentTableMetadata.EntityName);

            
            #line default
            #line hidden
WriteLiteral(" ");


            
            #line 79 "..\..\Templates\Entities\Poco.NHibernate.Designer.cshtml"
                                                         Write(reference.ParentPropertyName);

            
            #line default
            #line hidden
WriteLiteral(" { get; set; }\r\n\t\t");


            
            #line 80 "..\..\Templates\Entities\Poco.NHibernate.Designer.cshtml"
         }

            
            #line default
            #line hidden
WriteLiteral("\t\t\r\n\t\t#endregion\r\n\t\t\r\n\t\t#region \"Incoming References\"\r\n\t\t\r\n");


            
            #line 86 "..\..\Templates\Entities\Poco.NHibernate.Designer.cshtml"
 		foreach (var reference in this.TableMetadata.IncomingReferences)
		{
            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 88 "..\..\Templates\Entities\Poco.NHibernate.Designer.cshtml"
  		 var childObjParamName = reference.ChildTableMetadata.EntityName.Substring(0, 1).ToLower() + reference.ChildTableMetadata.EntityName.Substring(1); 

            
            #line default
            #line hidden
WriteLiteral("\t\t/// <summary>\r\n\t\t/// Field for the child list of Ref: ");


            
            #line 90 "..\..\Templates\Entities\Poco.NHibernate.Designer.cshtml"
                                   Write(reference.Name);

            
            #line default
            #line hidden
WriteLiteral(".\r\n\t\t/// </summary>\r\n\t\tpublic virtual IList<");


            
            #line 92 "..\..\Templates\Entities\Poco.NHibernate.Designer.cshtml"
                   Write(reference.ChildTableMetadata.EntityName);

            
            #line default
            #line hidden
WriteLiteral("> ");


            
            #line 92 "..\..\Templates\Entities\Poco.NHibernate.Designer.cshtml"
                                                               Write(reference.ChildListPropertyName);

            
            #line default
            #line hidden
WriteLiteral(" { get; set; }\r\n\t\t\r\n\t\t/// <summary>\r\n\t\t/// Add ");


            
            #line 95 "..\..\Templates\Entities\Poco.NHibernate.Designer.cshtml"
      Write(reference.ChildTableMetadata.EntityName);

            
            #line default
            #line hidden
WriteLiteral(" entity to ");


            
            #line 95 "..\..\Templates\Entities\Poco.NHibernate.Designer.cshtml"
                                                           Write(reference.ChildListPropertyName);

            
            #line default
            #line hidden
WriteLiteral(".\r\n\t\t/// </summary>\r\n\t\t/// <param name=\"");


            
            #line 97 "..\..\Templates\Entities\Poco.NHibernate.Designer.cshtml"
               Write(childObjParamName);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n\t\t///\tThe ");


            
            #line 98 "..\..\Templates\Entities\Poco.NHibernate.Designer.cshtml"
      Write(reference.ChildTableMetadata.EntityName);

            
            #line default
            #line hidden
WriteLiteral(" entity.\r\n\t\t/// </param>\r\n\t\tpublic virtual void AddTo");


            
            #line 100 "..\..\Templates\Entities\Poco.NHibernate.Designer.cshtml"
                       Write(reference.ChildListPropertyName);

            
            #line default
            #line hidden
WriteLiteral("(");


            
            #line 100 "..\..\Templates\Entities\Poco.NHibernate.Designer.cshtml"
                                                          Write(reference.ChildTableMetadata.EntityName);

            
            #line default
            #line hidden
WriteLiteral(" ");


            
            #line 100 "..\..\Templates\Entities\Poco.NHibernate.Designer.cshtml"
                                                                                                     Write(childObjParamName);

            
            #line default
            #line hidden
WriteLiteral(")\r\n\t\t{\r\n\t\t\t");


            
            #line 102 "..\..\Templates\Entities\Poco.NHibernate.Designer.cshtml"
Write(childObjParamName);

            
            #line default
            #line hidden
WriteLiteral(".");


            
            #line 102 "..\..\Templates\Entities\Poco.NHibernate.Designer.cshtml"
                    Write(reference.ParentPropertyName);

            
            #line default
            #line hidden
WriteLiteral(" = this;\r\n\t\t\tthis.");


            
            #line 103 "..\..\Templates\Entities\Poco.NHibernate.Designer.cshtml"
    Write(reference.ChildListPropertyName);

            
            #line default
            #line hidden
WriteLiteral(".Add(");


            
            #line 103 "..\..\Templates\Entities\Poco.NHibernate.Designer.cshtml"
                                           Write(childObjParamName);

            
            #line default
            #line hidden
WriteLiteral(");\r\n\t\t}\r\n\t\t");


            
            #line 105 "..\..\Templates\Entities\Poco.NHibernate.Designer.cshtml"
         }

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t#endregion\r\n\t\t\r\n\r\n\t}\r\n}");


        }
    }
}
#pragma warning restore 1591
