// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Tangsem.Generator.Templates.MVC.Controllers
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using Tangsem.Common.Extensions;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\MVC\Controllers\ApiControllerTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class ApiControllerTemplate : ApiControllerTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("\r\n");
            
            #line 8 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\MVC\Controllers\ApiControllerTemplate.tt"

	var tableMetadata = this.TableMetadata;

            
            #line default
            #line hidden
            this.Write("\r\nusing System.Linq;\r\nusing Microsoft.AspNetCore.Mvc;\r\nusing AutoMapper;\r\nusing ");
            
            #line 15 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\MVC\Controllers\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Configuration.RepositoryNamespace));
            
            #line default
            #line hidden
            this.Write(";\r\nusing ");
            
            #line 16 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\MVC\Controllers\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Configuration.EntityNamespace));
            
            #line default
            #line hidden
            this.Write(";\r\nusing ");
            
            #line 17 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\MVC\Controllers\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Configuration.DTONamespace));
            
            #line default
            #line hidden
            this.Write(";\r\nusing ");
            
            #line 18 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\MVC\Controllers\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Configuration.DomainNamespace));
            
            #line default
            #line hidden
            this.Write(".ViewModels.SearchParams;\r\n\r\nusing Tangsem.Data;\r\nusing Tangsem.NHibernate.Extens" +
                    "tions;\r\nusing ");
            
            #line 22 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\MVC\Controllers\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Configuration.RootProjectName));
            
            #line default
            #line hidden
            this.Write(".Host.Filters;\r\nusing ");
            
            #line 23 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\MVC\Controllers\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Configuration.RootProjectName));
            
            #line default
            #line hidden
            this.Write(".Host.Controllers.Base;\r\n\r\nnamespace ");
            
            #line 25 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\MVC\Controllers\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Configuration.RootProjectName));
            
            #line default
            #line hidden
            this.Write(".Host.Controllers\r\n{\r\n\tpublic partial class ");
            
            #line 27 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\MVC\Controllers\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write("ApiController : ");
            
            #line 27 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\MVC\Controllers\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write("ApiControllerBase\r\n\t{\t\r\n\t\tpublic ");
            
            #line 29 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\MVC\Controllers\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write("ApiController(I");
            
            #line 29 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\MVC\Controllers\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Configuration.RepositoryName));
            
            #line default
            #line hidden
            this.Write(" repository, IMapper mapper): base(repository, mapper) {\r\n\t\t}\r\n\r\n\t\t[HttpGet(\"_api" +
                    "/repo/");
            
            #line 32 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\MVC\Controllers\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write("\")]\r\n\t\tpublic override IActionResult Get");
            
            #line 33 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\MVC\Controllers\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write("List(");
            
            #line 33 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\MVC\Controllers\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write("SearchParams filterModel) {\r\n            return base.Get");
            
            #line 34 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\MVC\Controllers\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write("List(filterModel);\r\n\t\t}\r\n     \r\n\t\t[HttpGet(\"_api/repo/");
            
            #line 37 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\MVC\Controllers\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write("/{id}\")]\r\n\t\tpublic override IActionResult Get");
            
            #line 38 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\MVC\Controllers\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write("By");
            
            #line 38 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\MVC\Controllers\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.PrimaryKeyPropertyName));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 38 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\MVC\Controllers\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.PrimaryKeyCSharpTypeAsString));
            
            #line default
            #line hidden
            this.Write(" id) {\r\n\t\t\treturn base.Get");
            
            #line 39 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\MVC\Controllers\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write("By");
            
            #line 39 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\MVC\Controllers\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.PrimaryKeyPropertyName));
            
            #line default
            #line hidden
            this.Write("(id);\r\n\t\t}\r\n\r\n\t\t[HttpPost(\"_api/repo/");
            
            #line 42 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\MVC\Controllers\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write("/{id}\")]\r\n\t\t[TransactionFilter]\r\n\t\tpublic override IActionResult Update");
            
            #line 44 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\MVC\Controllers\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 44 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\MVC\Controllers\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.PrimaryKeyCSharpTypeAsString));
            
            #line default
            #line hidden
            this.Write(" id, [FromBody] ");
            
            #line 44 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\MVC\Controllers\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write("DTO model) {\r\n\t\t    return base.Update");
            
            #line 45 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\MVC\Controllers\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write("(id, model);\r\n\t\t}\r\n     \r\n\t\t[HttpPost(\"_api/repo/");
            
            #line 48 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\MVC\Controllers\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write("\")]\r\n\t\t[TransactionFilter]\r\n\t\tpublic override IActionResult Create");
            
            #line 50 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\MVC\Controllers\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write("([FromBody] ");
            
            #line 50 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\MVC\Controllers\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write("DTO model) {\r\n\t\t\treturn base.Create");
            
            #line 51 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\MVC\Controllers\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write("(model);\r\n\t\t}\r\n\r\n\t\t[HttpPost(\"_api/repo/");
            
            #line 54 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\MVC\Controllers\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write("/{id}/delete\")]\r\n\t\t[TransactionFilter]\r\n\t\tpublic override IActionResult Delete");
            
            #line 56 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\MVC\Controllers\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 56 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\MVC\Controllers\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.PrimaryKeyCSharpTypeAsString));
            
            #line default
            #line hidden
            this.Write(" id, bool isHardDelete) {\r\n            return base.Delete");
            
            #line 57 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\MVC\Controllers\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write("(id, isHardDelete);\r\n\t\t}\r\n\r\n\t\tpublic override IQueryable<");
            
            #line 60 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\MVC\Controllers\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write("> FilterBySearchParams(IQueryable<");
            
            #line 60 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\MVC\Controllers\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write("> qry, ");
            
            #line 60 "C:\git-temp\tangsem.suite\Tangsem.Suite\projects\Tangsem.Generator\Templates\MVC\Controllers\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableMetadata.EntityName));
            
            #line default
            #line hidden
            this.Write("SearchParams filterModel) {\r\n            return base.FilterBySearchParams(qry, fi" +
                    "lterModel);\r\n\t\t}\r\n\t}\r\n\r\n}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public class ApiControllerTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
